import type { Group, GroupContext, ListFilters, PersonContext, Snapshot, classesList, familiesList, studentsList } from "./relationships.js";
import { candidateList, chip, chips, dateRange, emptyState, escape as e, graphEmpty, hidden, layout, notice, pageHead, pager, personHref, personLink, pill, relationshipGraph, relationshipLabel, selectOptions, statePill, statusPill, type GraphNode, type GraphTier } from "./views.js";
export type Section = "families" | "students" | "classes";
export const sectionNames: Record<Section, [string, string]> = { families: ["Families", "family"], students: ["Students", "student"], classes: ["Classes", "class"] };
export type PageOptions = { saved?: boolean; created?: boolean; error?: string; add?: string };
const saveForm = (version: string, kind: string, returnTo: string, extra: Record<string, string>, body: string, cls = "inline") =>
  `<form class="${cls}" method="post" action="/admin/directory/save">${kind ? hidden("kind", kind) : ""}${hidden("version", version)}${hidden("returnTo", returnTo)}${Object.entries(extra).map(([k, v]) => hidden(k, v)).join("")}${body}</form>`;
const flashes = (o: PageOptions, savedText = "Directory saved. Updated relationships apply on the next application access check.") => `${o.saved ? notice(savedText) : ""}${o.created ? notice("Adult account created and pre-approved. You can add them below.") : ""}${o.error ? notice(o.error, "error") : ""}`;
const filterLink = (base: string, f: Record<string, string | number | undefined>) => (p: number) => `${base}?${new URLSearchParams(Object.fromEntries(Object.entries({ ...f, page: p }).filter(([, v]) => v !== undefined && String(v) !== "").map(([k, v]) => [k, String(v)])))}`;
const names = (people: { id: string; kind: string; displayName: string }[], empty: string) => people.length ? people.map(p => `<a href="${personHref(p)}">${e(p.displayName)}</a>`).join(", ") : `<span class="muted">${e(empty)}</span>`;
// ---- Lists ------------------------------------------------------------------
export function studentsListView(list: ReturnType<typeof studentsList>, f: ListFilters) {
  const link = filterLink("/admin/students", { q: f.q, classId: f.classId, familyId: f.familyId, needs: f.needs, status: f.status });
  return layout("Students", `${pageHead({ eyebrow: "Directory", title: "Students", lede: "Student records never sign in. Their families and classes decide which parents and teachers can see them in connected applications.", actions: `<a class="btn" href="/admin/families/wizard">New family setup</a><a class="btn secondary" href="/admin/students/new">+ Add student</a>` })}
<form class="card filters" method="get" action="/admin/students"><div class="grow"><label for="q">Search</label><input id="q" name="q" type="search" placeholder="Student name" value="${e(f.q)}" maxlength="120"></div><div><label for="classId">Class</label><select id="classId" name="classId"><option value="">Any class</option>${list.classes.map(c => `<option value="${c.id}" ${c.id === f.classId ? "selected" : ""}>${e(c.displayName)}</option>`).join("")}</select></div><div><label for="familyId">Family</label><select id="familyId" name="familyId"><option value="">Any family</option>${list.families.map(x => `<option value="${x.id}" ${x.id === f.familyId ? "selected" : ""}>${e(x.displayName)}</option>`).join("")}</select></div><div><label for="needs">Show</label><select id="needs" name="needs">${selectOptions([["", "Everyone"], ["class", "Not in any class"], ["family", "Not in any family"]], f.needs ?? "")}</select></div><div><label for="status">Status</label><select id="status" name="status">${selectOptions([["", "Any"], ["active", "Active"], ["disabled", "Disabled"]], f.status ?? "")}</select></div><button>Apply</button><a href="/admin/students">Reset</a></form>
<div class="card table-card">${list.rows.length ? `<table><thead><tr><th>Student</th><th>Families</th><th>Classes</th><th>Status</th></tr></thead><tbody>${list.rows.map(p => `<tr><td>${personLink(p)}</td><td>${chips(p.summary.families.map(x => chip(`/admin/families/${x.id}`, x.name)), "No family")}</td><td>${chips(p.summary.classes.map(x => chip(`/admin/classes/${x.id}`, x.name)), "Not enrolled")}</td><td>${statusPill(p.status)}</td></tr>`).join("")}</tbody></table>` : emptyState("No students match", '<p>Adjust the filters or <a href="/admin/students/new">add a student</a>.</p>')}</div>${pager(list.total, list.page, list.pages, link, "student")}`, true, "students");
}
export function familiesListView(list: ReturnType<typeof familiesList>, f: ListFilters) {
  const link = filterLink("/admin/families", { q: f.q, needs: f.needs, status: f.status });
  return layout("Families", `${pageHead({ eyebrow: "Directory", title: "Families", lede: "A family connects parents and guardians to their children. Open a family to add members, end memberships, or create a child directly inside it.", actions: `<a class="btn" href="/admin/families/wizard">New family setup</a><a class="btn secondary" href="/admin/families/new">+ Add family</a>` })}
<form class="card filters" method="get" action="/admin/families"><div class="grow"><label for="q">Search</label><input id="q" name="q" type="search" placeholder="Family name, code, or member name" value="${e(f.q)}" maxlength="120"></div><div><label for="needs">Show</label><select id="needs" name="needs">${selectOptions([["", "All families"], ["guardian", "Without a parent or guardian"], ["children", "Without children"]], f.needs ?? "")}</select></div><div><label for="status">Status</label><select id="status" name="status">${selectOptions([["", "Any"], ["active", "Active"], ["disabled", "Disabled"]], f.status ?? "")}</select></div><button>Apply</button><a href="/admin/families">Reset</a></form>
<div class="card table-card">${list.rows.length ? `<table><thead><tr><th>Family</th><th>Parents &amp; guardians</th><th>Children</th><th>Status</th></tr></thead><tbody>${list.rows.map(x => `<tr><td><a class="name" href="/admin/families/${x.id}">${e(x.displayName)}</a><small>${e(x.code)}</small></td><td>${names(x.guardians, "None")}</td><td>${names(x.children, "None")}</td><td>${statusPill(x.status)}</td></tr>`).join("")}</tbody></table>` : emptyState("No families match", '<p>Adjust the filters, start a <a href="/admin/families/wizard">family setup</a>, or <a href="/admin/families/new">add a family</a>.</p>')}</div>${pager(list.total, list.page, list.pages, link, "family")}`, true, "families");
}
export function classesListView(list: ReturnType<typeof classesList>, f: ListFilters) {
  const link = filterLink("/admin/classes", { q: f.q, needs: f.needs, status: f.status });
  return layout("Classes", `${pageHead({ eyebrow: "Directory", title: "Classes", lede: "Class codes match the CMS. Open a class to enroll students in bulk, assign teachers, or move students to another class.", actions: `<a class="btn secondary" href="/admin/classes/new">+ Add class</a>` })}
<form class="card filters" method="get" action="/admin/classes"><div class="grow"><label for="q">Search</label><input id="q" name="q" type="search" placeholder="Class name, code, or teacher" value="${e(f.q)}" maxlength="120"></div><div><label for="needs">Show</label><select id="needs" name="needs">${selectOptions([["", "All classes"], ["teacher", "Without a teacher"]], f.needs ?? "")}</select></div><div><label for="status">Status</label><select id="status" name="status">${selectOptions([["", "Any"], ["active", "Active"], ["disabled", "Disabled"]], f.status ?? "")}</select></div><button>Apply</button><a href="/admin/classes">Reset</a></form>
<div class="card table-card">${list.rows.length ? `<table><thead><tr><th>Class</th><th>Teachers</th><th class="right">Students</th><th>Status</th></tr></thead><tbody>${list.rows.map(c => `<tr><td><a class="name" href="/admin/classes/${c.id}">${e(c.displayName)}</a><small>${e(c.code)}</small></td><td>${names(c.teachers, "No teacher")}</td><td class="num">${c.studentCount}</td><td>${statusPill(c.status)}</td></tr>`).join("")}</tbody></table>` : emptyState("No classes match", '<p>Adjust the filters or <a href="/admin/classes/new">add a class</a>.</p>')}</div>${pager(list.total, list.page, list.pages, link, "class")}`, true, "classes");
}
// ---- Create / edit basic record ------------------------------------------------
export function recordFormView(section: Section, record: Group | { id: string; displayName: string; status: string } | null, data: Snapshot, o: PageOptions & { values?: Record<string, unknown> } = {}) {
  const [plural, singular] = sectionNames[section];
  const v = o.values ?? {};
  const value = (key: string, fallback?: string) => e(typeof v[key] === "string" ? v[key] : fallback ?? "");
  const title = record ? record.displayName : `Add ${singular}`;
  const back = record ? `/admin/${section}/${record.id}` : `/admin/${section}`;
  const code = section !== "students" ? record && "code" in record ? `<div class="field"><label>Code</label><input type="text" value="${e(record.code)}" readonly>${hidden("code", record.code)}<small>Codes are fixed after creation because connected applications map by code.</small></div>` : `<div class="field"><label for="code">${section === "classes" ? "Class code" : "Family code"}</label><input id="code" name="code" type="text" value="${value("code")}" required maxlength="40" pattern="[A-Za-z0-9][A-Za-z0-9_\\-]{0,39}"><small>${section === "classes" ? "Use the same class code as the CMS." : "Short, unique and stable, e.g. F-CHAN-2026."} Letters, numbers, underscores and hyphens.</small></div>` : "";
  const linkOnCreate = section === "students" && !record ? `<div class="field"><label for="groupId">Add to (optional)</label><select id="groupId" name="groupId"><option value="">Nothing yet</option><optgroup label="Families — as child">${data.families.filter(f => f.status === "active").sort((a, b) => a.displayName.localeCompare(b.displayName)).map(f => `<option value="${f.id}" ${v.groupId === f.id ? "selected" : ""}>${e(f.displayName)} (${e(f.code)})</option>`).join("")}</optgroup><optgroup label="Classes — as student">${data.classes.filter(c => c.status === "active").sort((a, b) => a.displayName.localeCompare(b.displayName)).map(c => `<option value="${c.id}" ${v.groupId === c.id ? "selected" : ""}>${e(c.displayName)} (${e(c.code)})</option>`).join("")}</optgroup></select><small>You can add more families and classes from the student's page afterwards.</small></div>` : "";
  return layout(title, `${pageHead({ crumbs: [[plural, `/admin/${section}`], ...(record ? [[record.displayName, back] as [string, string]] : []), [record ? "Edit details" : title]], eyebrow: record ? `${relationshipLabel(singular)} details` : `New ${singular}`, title })}${flashes(o)}
<div class="split"><section class="card">${saveForm(data.version, section, record ? back : "", { id: record?.id ?? "" }, `<div class="field"><label for="displayName">Name</label><input id="displayName" name="displayName" type="text" value="${value("displayName", record?.displayName)}" required maxlength="120"></div>${code}${linkOnCreate}<div class="field"><label for="status">Status</label><select id="status" name="status">${selectOptions([["active", "Active"], ["disabled", "Disabled"]], String(v.status ?? record?.status ?? "active"))}</select><small>${section === "students" ? "Disabled students disappear from parents' and teachers' views without deleting history." : `Disabled ${plural.toLowerCase()} stop granting access without deleting memberships.`}</small></div><div class="actions"><button>${record ? "Save changes" : `Create ${singular}`}</button><a class="btn ghost" href="${back}">Cancel</a></div>`, "")}</section>
<section class="card"><h2>What happens next</h2><p class="lede">${section === "students" ? "Students never receive a login. After creating the record, open it to connect families and classes — or use the family setup wizard to create a student, family and class links in one flow." : section === "families" ? "After creating the family, add parents and guardians from existing adult accounts, then add children. You can also create new children directly on the family page." : "After creating the class, enroll students in bulk from the class page and assign a teacher. Students can be moved between classes without losing history."}</p>${section !== "students" ? '<p class="muted">Codes cannot be edited later. Names and status can.</p>' : ""}</section></div>`, true, section);
}
// ---- Relationship graphs ---------------------------------------------------------
const graphCard = (graph: string) => `<section class="card"><div class="card-head"><h2>Relationship graph</h2><span class="muted">Click a node to open it</span></div>${graph}</section>`;
const memberNode = (l: GroupContext["adults"][number], meta: string): GraphNode => ({ title: l.person.displayName, meta: `${meta}${l.state === "scheduled" ? " · scheduled" : ""}`, href: personHref(l.person), kind: l.person.kind === "student" ? "student" : "adult", dim: l.state !== "active" || l.person.status !== "active" });
/** Distinct groups reachable through a set of members, with how many members connect to each. */
function reachedGroups(members: GroupContext["adults"], pick: (s: GroupContext["adults"][number]["summary"]) => { id: string; name: string }[], kind: "family" | "class", section: string): GraphNode[] {
  const counts = new Map<string, { name: string; count: number }>();
  for (const m of members) for (const g of pick(m.summary)) counts.set(g.id, { name: g.name, count: (counts.get(g.id)?.count ?? 0) + 1 });
  return [...counts].sort((a, b) => a[1].name.localeCompare(b[1].name)).map(([id, g]) => ({ title: g.name, meta: `${g.count} ${kind === "class" ? "child" : "student"}${g.count === 1 ? "" : kind === "class" ? "ren" : "s"} here`, href: `/admin/${section}/${id}`, kind }));
}
function familyGraph(ctx: GroupContext) {
  const g = ctx.group!;
  const tiers: GraphTier[] = [
    { label: "Parents & guardians", nodes: ctx.adults.length ? ctx.adults.map(l => memberNode(l, relationshipLabel(l.relationship))) : [graphEmpty("No parent or guardian yet")] },
    { edge: "members of", nodes: [{ title: g.displayName, meta: `Family · ${g.code}`, kind: "focus" }] },
    { edge: "children", label: "Children", nodes: ctx.students.length ? ctx.students.map(l => memberNode(l, l.summary.classes.length ? l.summary.classes.map(c => c.name).join(", ") : "Not enrolled")) : [graphEmpty("No children yet")] },
  ];
  const classes = reachedGroups(ctx.students, s => s.classes, "class", "classes");
  if (classes.length) tiers.push({ edge: "enrolled in", label: "Classes", nodes: classes });
  return relationshipGraph(tiers, `Relationships of ${g.displayName}`);
}
function classGraph(ctx: GroupContext) {
  const g = ctx.group!;
  const tiers: GraphTier[] = [
    { label: "Teachers", nodes: ctx.adults.length ? ctx.adults.map(l => memberNode(l, "Teacher")) : [graphEmpty("No teacher assigned")] },
    { edge: "teach", nodes: [{ title: g.displayName, meta: `Class · ${g.code}`, kind: "focus" }] },
    { edge: "students", label: "Students", nodes: ctx.students.length ? ctx.students.map(l => memberNode(l, l.summary.families.length ? l.summary.families.map(f => f.name).join(", ") : "No family")) : [graphEmpty("No students enrolled")] },
  ];
  const families = reachedGroups(ctx.students, s => s.families, "family", "families");
  if (families.length) tiers.push({ edge: "belong to", label: "Families", nodes: families });
  return relationshipGraph(tiers, `Relationships of ${g.displayName}`);
}
function studentGraph(ctx: PersonContext) {
  const p = ctx.person!;
  const live = (s: string) => s === "active" || s === "scheduled";
  const families = ctx.familyLinks.filter(l => live(l.state)), classes = ctx.classLinks.filter(l => live(l.state));
  const guardians = ctx.related.filter(r => r.relationship !== "child"), siblings = ctx.related.filter(r => r.relationship === "child");
  const tiers: GraphTier[] = [
    { label: "Parents & guardians", nodes: guardians.length ? guardians.map(r => ({ title: r.person.displayName, meta: `${relationshipLabel(r.relationship)} · ${r.family.displayName}`, href: personHref(r.person), kind: "adult" as const })) : [graphEmpty(families.length ? "No parent or guardian in these families" : "No parents or guardians")] },
    { edge: "members of", label: "Families", nodes: families.length ? families.map(l => ({ title: l.group.displayName, meta: `${l.group.code}${siblings.some(s => s.familyId === l.familyId) ? ` · siblings: ${siblings.filter(s => s.familyId === l.familyId).map(s => s.person.displayName).join(", ")}` : ""}${l.state === "scheduled" ? " · scheduled" : ""}`, href: `/admin/families/${l.group.id}`, kind: "family" as const, dim: l.state !== "active" })) : [graphEmpty("Not in any family yet")] },
    { edge: "child", nodes: [{ title: p.displayName, meta: "Student", kind: "focus" }] },
    { edge: "enrolled in", label: "Classes", nodes: classes.length ? classes.map(l => ({ title: l.group.displayName, meta: `${l.group.code} · ${l.teachers.length ? `taught by ${l.teachers.join(", ")}` : "no teacher"}${l.state === "scheduled" ? " · scheduled" : ""}`, href: `/admin/classes/${l.group.id}`, kind: "class" as const, dim: l.state !== "active" })) : [graphEmpty("Not enrolled in any class")] },
  ];
  return relationshipGraph(tiers, `Relationships of ${p.displayName}`);
}
// ---- Family detail --------------------------------------------------------------
export function familyDetailView(ctx: GroupContext, o: PageOptions) {
  const g = ctx.group!, here = `/admin/families/${g.id}`;
  const form = (kind: string, extra: Record<string, string>, body: string, cls?: string) => saveForm(ctx.version, kind, here, extra, body, cls);
  const memberRow = (l: GroupContext["adults"][number], showClasses: boolean) => `<tr><td>${personLink(l.person)}<small>${e(l.person.normalizedLoginEmail || (l.person.kind === "student" ? "Student" : "No login email"))}</small></td><td>${relationshipLabel(l.relationship)}</td><td>${statePill(l.state)}${l.person.status !== "active" ? ` ${pill("Person disabled", "warn")}` : ""}<small>${e(dateRange(l))}</small></td>${showClasses ? `<td>${chips(l.summary.classes.map(x => chip(`/admin/classes/${x.id}`, x.name)), "Not enrolled")}</td>` : ""}<td class="right"><div class="inline"><details class="row-edit"><summary>Dates</summary><div class="body">${form("family-member", { id: l.id, groupId: g.id, personId: l.personId, relationship: l.relationship, status: "active" }, `<div class="row"><div class="field"><label>From<input type="date" name="startsOn" value="${e(l.startsOn ?? "")}"></label></div><div class="field"><label>Through<input type="date" name="endsOn" value="${e(l.endsOn ?? "")}"></label></div><div class="field fixed"><button class="sm secondary">Save</button></div></div>`, "")}</div></details>${form("end-memberships", { membershipIds: l.id }, `<button class="danger sm" aria-label="End ${e(l.person.displayName)}'s membership">End</button>`)}</div></td></tr>`;
  const table = (rows: GroupContext["adults"], empty: string, showClasses: boolean) => rows.length ? `<div class="table-card card"><table><thead><tr><th>Person</th><th>Relationship</th><th>Status</th>${showClasses ? "<th>Classes</th>" : ""}<th></th></tr></thead><tbody>${rows.map(l => memberRow(l, showClasses)).join("")}</tbody></table></div>` : `<p class="muted">${e(empty)}</p>`;
  const q = o.add ?? "";
  const candidates = q ? ctx.candidates.length ? candidateList(ctx.candidates.map(p => ({
    head: personLink(p), meta: e(p.kind === "student" ? "Student" : `${p.normalizedLoginEmail ?? ""} · ${p.roles.map(relationshipLabel).join(", ") || "no roles"}`),
    chips: [...p.summary.families.map(x => chip(`/admin/families/${x.id}`, x.name, relationshipLabel(x.relationship))), ...p.summary.classes.map(x => chip(`/admin/classes/${x.id}`, x.name))].join(""),
    action: p.kind === "student" ? form("family-member", { groupId: g.id, personIds: p.id, relationship: "child", status: "active" }, `<button class="sm">Add as child</button>`) : form("family-member", { groupId: g.id, personIds: p.id, status: "active" }, `<select name="relationship" aria-label="Relationship for ${e(p.displayName)}">${selectOptions([["mother", "Mother"], ["father", "Father"], ["guardian", "Guardian"]], "guardian")}</select><button class="sm">Add</button>`),
  }))) : `<p class="muted" style="margin-top:12px">No active person matches “${e(q)}” who is not already in this family.</p>` : "";
  const manage = g.status === "active";
  return layout(g.displayName, `${pageHead({ crumbs: [["Families", "/admin/families"], [g.displayName]], eyebrow: "Family", title: g.displayName, titleExtra: statusPill(g.status), lede: `Code <strong>${e(g.code)}</strong> · ${ctx.adults.length} parent${ctx.adults.length === 1 ? "" : "s"} or guardian${ctx.adults.length === 1 ? "" : "s"}, ${ctx.students.length} child${ctx.students.length === 1 ? "" : "ren"}`, actions: `<a class="btn ghost" href="${here}/edit">Edit details</a><a class="btn secondary" href="/admin/families/wizard">New family setup</a>` })}${flashes(o)}${!manage ? notice("This family is disabled. Its memberships no longer grant access. Re-enable it under Edit details to manage members.", "warn") : ""}
${graphCard(familyGraph(ctx))}<div class="split wide"><div><section class="card"><div class="card-head"><h2>Parents &amp; guardians</h2>${ctx.adults.length ? "" : pill("Needs a guardian", "warn")}</div>${table(ctx.adults, "No parents or guardians yet. Add one on the right.", false)}</section><section class="card"><div class="card-head"><h2>Children</h2>${ctx.students.length ? "" : pill("No children", "neutral")}</div>${table(ctx.students, "No children yet. Add an existing student or create one on the right.", true)}</section>
${ctx.history.length ? `<details class="panel"><summary>Membership history (${ctx.history.length})</summary><div class="body"><div class="table-card card"><table><thead><tr><th>Person</th><th>Relationship</th><th>Status</th><th></th></tr></thead><tbody>${ctx.history.map(l => `<tr><td>${personLink(l.person)}</td><td>${relationshipLabel(l.relationship)}</td><td>${statePill(l.state)}<small>${e(dateRange(l))}</small></td><td class="right">${l.state === "inactive" && manage && l.person.status === "active" ? form("family-member", { id: l.id, groupId: g.id, personId: l.personId, relationship: l.relationship, status: "active", startsOn: l.startsOn ?? "", endsOn: l.endsOn ?? "" }, `<button class="ghost sm">Restore</button>`) : ""}</td></tr>`).join("")}</tbody></table></div></div></details>` : ""}</div>
<div>${manage ? `<section class="card"><h2>Add members</h2><p class="lede">Search existing adults and students. Adults join as mother, father or guardian; students join as children.</p><form class="row" method="get" action="${here}"><div class="field"><label for="add">Find a person</label><input id="add" name="add" type="search" value="${e(q)}" placeholder="Name or email" maxlength="120"></div><div class="field fixed"><button class="secondary">Search</button></div></form>${candidates}
<h3>Create a new child in this family</h3>${form("students", { groupId: g.id, status: "active" }, `<div class="row"><div class="field"><label for="newChild">Student name</label><input id="newChild" name="displayName" type="text" required maxlength="120" placeholder="Full name"></div><div class="field fixed"><button>Create and add</button></div></div>`, "")}
<h3>Need a new parent account?</h3><p class="muted">Pre-approve the adult first, then you will return here to add them. <a class="btn ghost sm" href="/admin/users/new?role=parent&amp;returnTo=${encodeURIComponent(here)}">Add adult account</a></p></section>` : ""}
<section class="card"><h2>Family details</h2><dl class="kv"><dt>Name</dt><dd>${e(g.displayName)}</dd><dt>Code</dt><dd>${e(g.code)}</dd><dt>Status</dt><dd>${statusPill(g.status)}</dd><dt>Updated</dt><dd>${e(g.updatedAt.toISOString().slice(0, 10))}</dd></dl><p style="margin-top:14px"><a class="btn ghost sm" href="${here}/edit">Edit details</a></p></section></div></div>`, true, "families");
}
// ---- Class detail ----------------------------------------------------------------
/** Checklist of unassigned teachers; opened by default when the class has none. */
function assignTeachers(ctx: GroupContext, form: (kind: string, extra: Record<string, string>, body: string, cls?: string) => string, open: boolean) {
  const g = ctx.group!;
  const body = ctx.availableTeachers.length
    ? form("class-member", { groupId: g.id, relationship: "teacher", status: "active" }, `${candidateList(ctx.availableTeachers.map(t => ({
        head: `<label class="check"><input type="checkbox" name="personIds" value="${t.id}"><span>${personLink(t)}<small>${e(t.normalizedLoginEmail ?? "")}</small></span></label>`,
        chips: t.summary.classes.map(c => chip(`/admin/classes/${c.id}`, c.name)).join("") || '<span class="muted">No classes yet</span>',
        action: "",
      })))}<div class="row" style="margin-top:12px"><div class="field fixed"><label for="teacherFrom">From (optional)</label><input id="teacherFrom" type="date" name="startsOn"></div><div class="field fixed"><label for="teacherTo">Through (optional)</label><input id="teacherTo" type="date" name="endsOn"></div><div class="field fixed"><button>Assign selected</button></div></div>`, "")
    : `<p class="muted">No unassigned adults with the Teacher role. Open an adult under <a href="/admin/users?kind=adult">Users</a>, tick the <strong>Teacher</strong> role and save, then return here — or <a href="/admin/users/new?role=teacher&amp;returnTo=${encodeURIComponent(`/admin/classes/${g.id}`)}">add a new teacher account</a>.</p>`;
  return `<details class="panel" ${open ? "open" : ""}><summary>Assign teachers${ctx.availableTeachers.length ? ` (${ctx.availableTeachers.length} available)` : ""}</summary><div class="body"><p class="muted" style="margin:0 0 10px">Adults with the Teacher role who are not yet assigned to this class. A class can have several teachers.</p>${body}</div></details>`;
}
export function classDetailView(ctx: GroupContext, o: PageOptions) {
  const g = ctx.group!, here = `/admin/classes/${g.id}`;
  const form = (kind: string, extra: Record<string, string>, body: string, cls?: string) => saveForm(ctx.version, kind, here, extra, body, cls);
  const manage = g.status === "active";
  const teacherRows = ctx.adults.map(l => `<tr><td>${personLink(l.person)}<small>${e(l.person.normalizedLoginEmail ?? "")}</small></td><td>${statePill(l.state)}<small>${e(dateRange(l))}</small></td><td>${chips(l.summary.classes.filter(x => x.id !== g.id).map(x => chip(`/admin/classes/${x.id}`, x.name)), "Only this class")}</td><td class="right">${form("end-memberships", { membershipIds: l.id }, `<button class="danger sm" aria-label="End ${e(l.person.displayName)}'s assignment">End</button>`)}</td></tr>`).join("");
  const studentRows = ctx.students.map(l => `<tr><td class="check-cell"><input type="checkbox" name="membershipIds" value="${l.id}" aria-label="Select ${e(l.person.displayName)}"></td><td>${personLink(l.person)}</td><td>${statePill(l.state)}${l.person.status !== "active" ? ` ${pill("Student disabled", "warn")}` : ""}<small>${e(dateRange(l))}</small></td><td>${chips(l.summary.families.map(x => chip(`/admin/families/${x.id}`, x.name)), "No family")}</td></tr>`).join("");
  const q = o.add ?? "";
  const pool = q ? ctx.candidates : ctx.unplacedStudents;
  const candidateRows = candidateList(pool.map(p => ({
    head: `<label class="check"><input type="checkbox" name="personIds" value="${p.id}"><span>${personLink(p)}<small>${e(p.kind === "student" ? "Student" : `${p.normalizedLoginEmail ?? ""} · Teacher`)}</small></span></label>`,
    chips: [...p.summary.families.map(x => chip(`/admin/families/${x.id}`, x.name)), ...p.summary.classes.map(x => chip(`/admin/classes/${x.id}`, x.name))].join("") || `<span class="muted">${p.kind === "student" ? "No family or class yet" : "No classes yet"}</span>`,
    action: "",
  })));
  return layout(g.displayName, `${pageHead({ crumbs: [["Classes", "/admin/classes"], [g.displayName]], eyebrow: "Class", title: g.displayName, titleExtra: statusPill(g.status), lede: `Code <strong>${e(g.code)}</strong> · ${ctx.students.length} student${ctx.students.length === 1 ? "" : "s"}, ${ctx.adults.length} teacher${ctx.adults.length === 1 ? "" : "s"}`, actions: `<a class="btn ghost" href="${here}/edit">Edit details</a>` })}${flashes(o)}${!manage ? notice("This class is disabled. Its memberships no longer grant access. Re-enable it under Edit details to manage members.", "warn") : ""}
${graphCard(classGraph(ctx))}<div class="split wide"><div><section class="card"><div class="card-head"><h2>Teachers</h2>${ctx.adults.length ? "" : pill("Needs a teacher", "warn")}</div>${teacherRows ? `<div class="table-card card"><table><thead><tr><th>Teacher</th><th>Status</th><th>Other classes</th><th></th></tr></thead><tbody>${teacherRows}</tbody></table></div>` : '<p class="muted">No teacher assigned yet.</p>'}${manage ? assignTeachers(ctx, form, !ctx.adults.length) : ""}</section>
<section class="card"><div class="card-head"><h2>Students</h2>${pill(`${ctx.students.length} enrolled`, ctx.students.length ? "ok" : "neutral")}</div>${studentRows ? form("", {}, `<div class="table-card card"><table><thead><tr><th class="check-cell"></th><th>Student</th><th>Status</th><th>Families</th></tr></thead><tbody>${studentRows}</tbody></table></div>${manage ? `<div class="row" style="margin-top:12px"><div class="field fixed"><label for="moveTo">With selected students</label><div class="inline"><button class="danger sm" name="kind" value="end-memberships">End enrollment</button>${ctx.otherClasses.length ? `<span class="muted">or move to</span><select id="moveTo" name="groupId"><option value="">Choose a class</option>${ctx.otherClasses.map(c => `<option value="${c.id}">${e(c.displayName)} (${e(c.code)})</option>`).join("")}</select><input type="date" name="startsOn" aria-label="Start date in the new class"><button class="secondary sm" name="kind" value="class-transfer">Move</button>` : ""}</div></div></div><p class="muted" style="margin-top:8px">Moving ends the enrollment here and starts a new one in the chosen class, keeping history.</p>` : ""}`, "") : '<p class="muted">No students enrolled yet.</p>'}</section>
${ctx.history.length ? `<details class="panel"><summary>Membership history (${ctx.history.length})</summary><div class="body"><div class="table-card card"><table><thead><tr><th>Person</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody>${ctx.history.map(l => `<tr><td>${personLink(l.person)}</td><td>${relationshipLabel(l.relationship)}</td><td>${statePill(l.state)}<small>${e(dateRange(l))}</small></td><td class="right">${l.state === "inactive" && manage && l.person.status === "active" ? form("class-member", { id: l.id, groupId: g.id, personId: l.personId, relationship: l.relationship, status: "active", startsOn: l.startsOn ?? "", endsOn: l.endsOn ?? "" }, `<button class="ghost sm">Restore</button>`) : ""}</td></tr>`).join("")}</tbody></table></div></div></details>` : ""}</div>
<div>${manage ? `<section class="card"><h2>Enroll students</h2><p class="lede">Search by name or email and select several to enroll together. Teachers are assigned from the Teachers card; adults with the Teacher role also appear in search results.</p><form class="row" method="get" action="${here}"><div class="field"><label for="add">Find people</label><input id="add" name="add" type="search" value="${e(q)}" placeholder="Name or email" maxlength="120"></div><div class="field fixed"><button class="secondary">Search</button></div></form>
${pool.length ? `<h3>${q ? `Matches for “${e(q)}”` : "Students not yet in any class"}</h3>${form("class-member", { groupId: g.id, status: "active" }, `${candidateRows}<div class="row" style="margin-top:12px"><div class="field fixed"><label for="enrollFrom">From (optional)</label><input id="enrollFrom" type="date" name="startsOn"></div><div class="field fixed"><label for="enrollTo">Through (optional)</label><input id="enrollTo" type="date" name="endsOn"></div><div class="field fixed"><button>Add selected</button></div></div>`, "")}` : q ? `<p class="muted">No eligible person matches “${e(q)}”. Teachers need the Teacher role under Users.</p>` : '<p class="muted">Every active student is already in a class. Search above to enroll a student from another class.</p>'}
<h3>Create a new student in this class</h3>${form("students", { groupId: g.id, status: "active" }, `<div class="row"><div class="field"><label for="newStudent">Student name</label><input id="newStudent" name="displayName" type="text" required maxlength="120" placeholder="Full name"></div><div class="field fixed"><button>Create and enroll</button></div></div>`, "")}</section>` : ""}
<section class="card"><h2>Class details</h2><dl class="kv"><dt>Name</dt><dd>${e(g.displayName)}</dd><dt>Code</dt><dd>${e(g.code)}</dd><dt>Status</dt><dd>${statusPill(g.status)}</dd><dt>Updated</dt><dd>${e(g.updatedAt.toISOString().slice(0, 10))}</dd></dl><p style="margin-top:14px"><a class="btn ghost sm" href="${here}/edit">Edit details</a> <a class="btn ghost sm" href="/admin/students?classId=${g.id}">View roster</a></p></section></div></div>`, true, "classes");
}
// ---- Student detail ---------------------------------------------------------------
export function studentDetailView(ctx: PersonContext, o: PageOptions & { values?: Record<string, unknown> }) {
  const p = ctx.person!, here = `/admin/students/${p.id}`;
  const form = (kind: string, extra: Record<string, string>, body: string, cls?: string) => saveForm(ctx.version, kind, here, extra, body, cls);
  const manage = p.status === "active";
  const v = o.values ?? {};
  const guardians = ctx.related.filter(r => r.relationship !== "child"), siblings = ctx.related.filter(r => r.relationship === "child");
  const endButton = (id: string, label: string) => form("end-memberships", { membershipIds: id }, `<button class="danger sm" aria-label="${e(label)}">End</button>`);
  const familyRows = ctx.familyLinks.map(l => `<tr><td><a class="name" href="/admin/families/${l.group.id}">${e(l.group.displayName)}</a><small>${e(l.group.code)}</small></td><td>${statePill(l.state)}<small>${e(dateRange(l))}</small></td><td class="right">${(l.state === "active" || l.state === "scheduled") ? endButton(l.id, `End membership in ${l.group.displayName}`) : l.state === "inactive" && manage && l.group.status === "active" ? form("family-member", { id: l.id, groupId: l.group.id, personId: p.id, relationship: l.relationship, status: "active", startsOn: l.startsOn ?? "", endsOn: l.endsOn ?? "" }, `<button class="ghost sm">Restore</button>`) : ""}</td></tr>`).join("");
  const classRows = ctx.classLinks.map(l => `<tr><td><a class="name" href="/admin/classes/${l.group.id}">${e(l.group.displayName)}</a><small>${e(l.group.code)}</small></td><td>${statePill(l.state)}<small>${e(dateRange(l))}</small></td><td class="right"><div class="inline">${(l.state === "active" || l.state === "scheduled") ? `<details class="row-edit"><summary>Dates</summary><div class="body">${form("class-member", { id: l.id, groupId: l.group.id, personId: p.id, relationship: l.relationship, status: "active" }, `<div class="row"><div class="field"><label>From<input type="date" name="startsOn" value="${e(l.startsOn ?? "")}"></label></div><div class="field"><label>Through<input type="date" name="endsOn" value="${e(l.endsOn ?? "")}"></label></div><div class="field fixed"><button class="sm secondary">Save</button></div></div>`, "")}</div></details>${endButton(l.id, `End enrollment in ${l.group.displayName}`)}` : l.state === "inactive" && manage && l.group.status === "active" ? form("class-member", { id: l.id, groupId: l.group.id, personId: p.id, relationship: l.relationship, status: "active", startsOn: l.startsOn ?? "", endsOn: l.endsOn ?? "" }, `<button class="ghost sm">Restore</button>`) : ""}</div></td></tr>`).join("");
  const q = o.add ?? "";
  const familySearch = manage ? `<details class="panel" ${q ? "open" : ""}><summary>Add to a family</summary><div class="body"><form class="row" method="get" action="${here}"><div class="field"><label for="add">Find a family</label><input id="add" name="add" type="search" value="${e(q)}" placeholder="Family name, code" maxlength="120"></div><div class="field fixed"><button class="secondary">Search</button></div></form>${q ? ctx.familyMatches.length ? candidateList(ctx.familyMatches.map(f => ({ head: `<a class="name" href="/admin/families/${f.id}">${e(f.displayName)}</a>`, meta: `${e(f.code)} · ${e(f.members.join(", ") || "No members yet")}`, action: form("family-member", { groupId: f.id, personIds: p.id, relationship: "child", status: "active" }, `<button class="sm">Add as child</button>`) }))) : `<p class="muted" style="margin-top:12px">No active family matches “${e(q)}”. <a href="/admin/families/new">Create a family</a>.</p>` : `<p class="muted" style="margin-top:10px">Search for the family, or <a href="/admin/families/wizard">run the family setup</a> to create parents and a family together.</p>`}</div></details>` : "";
  const enroll = manage ? ctx.classOptions.length ? `<details class="panel"><summary>Enroll in a class</summary><div class="body">${form("class-member", { personIds: p.id, relationship: "student", status: "active" }, `<div class="row"><div class="field"><label for="classId">Class</label><select id="classId" name="groupId" required><option value="">Choose a class</option>${ctx.classOptions.map(c => `<option value="${c.id}">${e(c.displayName)} (${e(c.code)})</option>`).join("")}</select></div><div class="field fixed"><label for="startsOn">From</label><input id="startsOn" type="date" name="startsOn"></div><div class="field fixed"><button>Enroll</button></div></div>`, "")}</div></details>` : '<p class="muted">Enrolled in every active class.</p>' : "";
  return layout(p.displayName, `${pageHead({ crumbs: [["Students", "/admin/students"], [p.displayName]], eyebrow: "Student", title: p.displayName, titleExtra: statusPill(p.status), lede: "Student record · no login account" })}${flashes(o)}${!manage ? notice("This student is disabled and hidden from parents' and teachers' views. Re-enable below to manage relationships.", "warn") : ""}
${graphCard(studentGraph(ctx))}<div class="split"><div><section class="card"><h2>Student details</h2>${form("students", { id: p.id }, `<div class="field"><label for="displayName">Name</label><input id="displayName" name="displayName" type="text" value="${e(typeof v.displayName === "string" ? v.displayName : p.displayName)}" required maxlength="120"></div><div class="field"><label for="status">Status</label><select id="status" name="status">${selectOptions([["active", "Active"], ["disabled", "Disabled"]], String(v.status ?? p.status))}</select></div><div class="actions"><button>Save changes</button></div>`, "")}</section>
<section class="card"><div class="card-head"><h2>Parents &amp; guardians</h2>${guardians.length ? "" : pill("None connected", "warn")}</div><p class="lede">Derived from this student's active families. Manage them on the family page.</p>${guardians.length ? `<ul class="plain people">${guardians.map(r => `<li><span>${personLink(r.person)}<small>${relationshipLabel(r.relationship)} · <a href="/admin/families/${r.family.id}">${e(r.family.displayName)}</a></small></span>${statusPill(r.person.status)}</li>`).join("")}</ul>` : '<p class="muted">No parent or guardian can currently see this student.</p>'}${siblings.length ? `<h3>Siblings</h3><ul class="plain people">${siblings.map(r => `<li><span>${personLink(r.person)}<small>${e(r.family.displayName)}</small></span></li>`).join("")}</ul>` : ""}</section></div>
<div><section class="card"><div class="card-head"><h2>Families</h2>${ctx.familyLinks.some(l => l.state === "active") ? pill("Connected", "ok") : pill("Needs a family", "warn")}</div>${familyRows ? `<div class="table-card card"><table><thead><tr><th>Family</th><th>Status</th><th></th></tr></thead><tbody>${familyRows}</tbody></table></div>` : '<p class="muted">Not in any family yet.</p>'}${familySearch}</section>
<section class="card"><div class="card-head"><h2>Classes</h2>${ctx.classLinks.some(l => l.state === "active") ? pill("Enrolled", "ok") : pill("Not enrolled", "warn")}</div>${classRows ? `<div class="table-card card"><table><thead><tr><th>Class</th><th>Status</th><th></th></tr></thead><tbody>${classRows}</tbody></table></div>` : '<p class="muted">Not enrolled in any class yet.</p>'}${enroll}</section></div></div>`, true, "students");
}
