import type { relationshipSnapshot } from "./relationships.js";
import { escape as e, layout } from "./views.js";
import { isDevelopmentIdentity } from "../development/policy.js";
type Data = Awaited<ReturnType<typeof relationshipSnapshot>>;
export type Section = "families" | "students" | "classes";
const names = { families: "Families", students: "Students", classes: "Classes" };
const hidden = (key: string, value: string) => `<input type="hidden" name="${key}" value="${e(value)}">`;
const input = (key: string, label: string, value = "", type = "text", required = false) => `<div class="field"><label>${label}<input name="${key}" type="${type}" value="${e(value)}" ${required ? 'required' : ''} maxlength="120" style="width:100%"></label></div>`;
const status = (value: string, membership = false) => `<label>Status<select name="status">${(membership ? ["active", "inactive"] : ["active", "disabled"]).map(s => `<option ${value === s ? "selected" : ""}>${s}</option>`).join("")}</select></label>`;
const formStart = (data: Data, section: string, kind: string, id = "") => `<form method="post" action="/admin/directory/save">${hidden("section", section)}${hidden("kind", kind)}${hidden("version", data.version)}${hidden("id", id)}`;
export function relationshipView(data: Data, section: Section, selected: string, q: string, saved: boolean) {
  const today = new Date().toISOString().slice(0,10);
  const effective = (l: { status: string; startsOn: string | null; endsOn: string | null }) => l.status === "active" && (!l.startsOn || l.startsOn <= today) && (!l.endsOn || l.endsOn >= today);
  const rows = section === "students" ? data.persons.filter(p => p.kind === "student") : data[section];
  const record = rows.find(r => r.id === selected);
  const sorted = rows.filter(r => `${r.displayName} ${"code" in r ? r.code : ""}`.toLowerCase().includes(q.toLowerCase())).sort((a,b) => a.displayName.localeCompare(b.displayName));
  const editor = record || selected === "new";
  let content = `<header><div><span class="eyebrow">School directory</span><h1>${names[section]}</h1><p>Create a family, add parents and students, then enroll students in classes. Students do not receive login accounts.</p></div>${section === "families" ? '<a class="button" href="/admin/families/wizard">New family setup</a>' : ""}<a class="button secondary" href="/admin/${section}?id=new">Add ${section === "families" ? "family" : section === "classes" ? "class" : "student"}</a></header>${saved ? '<div class="notice" role="status">Directory saved. Updated relationships apply on the next application access check.</div>' : ''}<form class="card toolbar" method="get"><label>Search<input name="q" value="${e(q)}" type="search"></label><button>Search</button><a href="/admin/${section}">Reset</a></form><div class="card table"><table><thead><tr><th>Name</th><th>${section === "students" ? "Families / classes" : "Code"}</th><th>Status</th><th></th></tr></thead><tbody>${sorted.map(r => `<tr><td>${e(r.displayName)}</td><td>${"code" in r ? e(r.code) : e([...data.familyLinks.filter(l => l.personId === r.id && effective(l)).map(l => data.families.find(f => f.id === l.familyId)?.displayName), ...data.classLinks.filter(l => l.personId === r.id && effective(l)).map(l => data.classes.find(c => c.id === l.classId)?.displayName)].filter(Boolean).join(", ") || "Not assigned")}</td><td>${e(r.status)}</td><td><a href="/admin/${section}?id=${r.id}">Manage</a></td></tr>`).join("") || '<tr><td colspan="4">No matching records.</td></tr>'}</tbody></table></div>`;
  if (editor) {
    content += `<section class="card"><h2>${record ? e(record.displayName) : "New record"}</h2>${formStart(data, section, section, record?.id)}${input("displayName", "Name", record?.displayName, "text", true)}${section !== "students" ? record && "code" in record ? `<p>Code: <strong>${e(record.code)}</strong></p>${hidden("code", record.code)}` : input("code", section === "classes" ? "Class code (match CMS class code)" : "Family code", "", "text", true) : '<p>This student record has no email, sign-in session, or password.</p>'}${status(record?.status || "active")}<p><button>Save ${section === "students" ? "student" : section === "families" ? "family" : "class"}</button></p></form></section>`;
  }
  if (record && section === "students") {
    content += `<section class="card"><h2>Assign relationships</h2><p>Open a family to add this student as a child, or a class to enroll this student.</p><p><a href="/admin/families">Manage families →</a> &nbsp; <a href="/admin/classes">Manage classes →</a></p></section>`;
  }
  if (record && section !== "students") {
    const family = section === "families", kind = family ? "family-member" : "class-member";
    const links = family ? data.familyLinks.filter(l => l.familyId === record.id) : data.classLinks.filter(l => l.classId === record.id);
    const candidates = data.persons.filter(p => p.status === "active" && !isDevelopmentIdentity(p.id) && (family || p.kind === "student" || data.roles.some(r => r.personId === p.id && r.role === "teacher"))).sort((a,b) => a.displayName.localeCompare(b.displayName));
    content += `<section class="card"><h2>${family ? "Parents, guardians and children" : "Students and teachers"}</h2><p>${family ? "Remove disconnects a person from this family while preserving their record and membership history." : "Dates are inclusive. Blank dates mean no boundary."} Set Inactive to end access immediately while preserving history.</p>${links.map(link => `<details><summary>${e(data.persons.find(p => p.id === link.personId)?.displayName || "Unknown person")} · ${e(link.relationship)} · ${e(link.status)}${!family && link.startsOn ? ` · from ${link.startsOn}` : ''}${!family && link.endsOn ? ` · through ${link.endsOn}` : ''}</summary>${formStart(data, section, kind, link.id)}${hidden("groupId", record.id)}${hidden("personId", link.personId)}${hidden("relationship", link.relationship)}${family ? hidden("startsOn", link.startsOn || "") + hidden("endsOn", link.endsOn || "") : input("startsOn", "Start date", link.startsOn || "", "date") + input("endsOn", "End date", link.endsOn || "", "date")}${status(link.status, true)}<p><button>Save membership</button></p></form>${family && link.status === "active" ? `${formStart(data, section, kind, link.id)}${hidden("groupId", record.id)}${hidden("personId", link.personId)}${hidden("relationship", link.relationship)}${hidden("startsOn", link.startsOn || "")}${hidden("endsOn", link.endsOn || "")}${hidden("status", "inactive")}<button class="secondary" aria-label="Remove ${e(data.persons.find(p => p.id === link.personId)?.displayName || "member")} from family">Remove</button></form>` : ""}</details>`).join("") || '<p>No members yet.</p>'}<h3>Add ${family ? "family member" : "enrollment or assignment"}</h3>${formStart(data, section, kind)}${hidden("groupId", record.id)}<label>Person<select name="personId" required><option value="">Choose a person</option>${candidates.map(p => `<option value="${p.id}">${e(p.displayName)} (${p.kind}${p.normalizedLoginEmail ? ` · ${e(p.normalizedLoginEmail)}` : ''})</option>`).join("")}</select></label><label>Relationship<select name="relationship">${(family ? ["father", "mother", "guardian", "child"] : ["student", "teacher"]).map(r => `<option>${r}</option>`).join("")}</select></label>${family ? "" : input("startsOn", "Start date", "", "date") + input("endsOn", "End date", "", "date")}${hidden("status", "active")}<button>Add member</button></form><p>${family ? '<a href="/admin/users/new">Add a parent login account</a> · <a href="/admin/students?id=new">Create a student</a>' : '<a href="/admin/students">Manage students</a> · <a href="/admin">Manage teacher roles</a>'}</p></section>`;
  }
  return layout(names[section], content);
}
