import type { adminService } from "./service.js";
import type { Insights, MembershipState, PersonContext } from "./relationships.js";
import { currentLocale, currentPath, label, localeNames, locales, t, tn } from "./i18n.js";
export const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const e = escape;
type Service = ReturnType<typeof adminService>;
export type NavKey = "overview" | "users" | "students" | "families" | "classes" | "applications";
const navigation: { group: string; items: [NavKey, string, string][] }[] = [
  { group: "Directory", items: [["overview", "/admin", "Overview"], ["users", "/admin/users", "Users"], ["students", "/admin/students", "Students"], ["families", "/admin/families", "Families"], ["classes", "/admin/classes", "Classes"]] },
  { group: "Integrations", items: [["applications", "/admin/applications", "Applications"]] },
];
export function accountMenu(person: { displayName: string; normalizedLoginEmail: string | null; roles: string[] }) {
  return `<details class="account-menu"><summary aria-label="${e(t("Signed-in account: {name}", { name: person.displayName }))}">${e(person.displayName)} <span aria-hidden="true">▾</span></summary><div class="account-details"><strong>${e(person.displayName)}</strong><dl class="kv"><dt>${e(t("Email"))}</dt><dd>${e(person.normalizedLoginEmail)}</dd><dt>${e(t("Roles"))}</dt><dd>${person.roles.map(r => e(label(r))).join(", ")}</dd></dl></div></details>`;
}
const css = `
:root{--bg:#f3f5f1;--card:#fff;--line:#dfe5dd;--line-soft:#eceee9;--text:#1f2a24;--muted:#66746b;--brand:#2e5844;--brand-deep:#1f3a30;--brand-soft:#e6efe6;--accent:#bd9144;--ok-bg:#e4f1e2;--ok:#2d5d38;--info-bg:#e7eef8;--info:#2f4d7a;--warn-bg:#fbf0dd;--warn:#87590f;--off-bg:#eeebe7;--off:#6f5a4c;--danger:#9a3b26;--danger-bg:#fbeae4;--radius:12px}
*{box-sizing:border-box}html{font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--text);background:var(--bg);line-height:1.5;font-size:15px}body{margin:0;min-height:100vh}
.shell{display:grid;grid-template-columns:236px minmax(0,1fr);min-height:100vh}.sidebar{background:var(--brand-deep);color:#e4ece3;display:flex;flex-direction:column;padding:22px 16px;gap:18px;position:sticky;top:0;height:100vh}.brand{color:white;font-weight:750;letter-spacing:.04em;padding:6px 10px;text-decoration:none}.brand span{font-weight:400;opacity:.65}
.sidebar nav{display:flex;flex-direction:column;gap:2px}.sidebar nav a{color:#d6e2d4;text-decoration:none;padding:9px 12px;border-radius:9px;font-size:14px}.sidebar nav a:hover{background:#ffffff14;color:white}.sidebar nav a[aria-current]{background:#ffffff22;color:white;font-weight:650}.sidebar .group{font-size:11px;text-transform:uppercase;letter-spacing:.12em;opacity:.55;padding:12px 12px 4px}
.sidebar-foot{margin-top:auto;display:flex;flex-direction:column;gap:10px}.sidebar-foot button{background:#ffffff14;color:white;width:100%;justify-content:center}.sidebar-foot button:hover{background:#ffffff26}
.lang-switch{display:flex;gap:4px;padding:3px;border-radius:9px;background:#ffffff10}.lang-switch button{flex:1;padding:6px 8px;font-size:12px;font-weight:600;background:transparent;color:#c9d6c7;border-radius:7px;width:auto}.lang-switch button:hover{background:#ffffff1a}.lang-switch button[aria-current]{background:#ffffff26;color:white;cursor:default}.solo .lang-switch{background:#e6ebe4;margin-bottom:16px;max-width:220px;margin-left:auto}.solo .lang-switch button{color:#4c5a51}.solo .lang-switch button:hover{background:#ffffffa0}.solo .lang-switch button[aria-current]{background:white;color:var(--text)}
.account-menu{position:relative}.account-menu summary{cursor:pointer;list-style:none;border-radius:8px;padding:8px 10px;font-size:14px;color:#e4ece3;overflow-wrap:anywhere;display:flex;justify-content:space-between;gap:8px;align-items:center}.account-menu summary::-webkit-details-marker{display:none}.account-menu summary:hover{background:#ffffff14}.account-details{position:absolute;left:0;bottom:calc(100% + 8px);z-index:20;width:280px;max-width:calc(100vw - 40px);padding:16px;border:1px solid var(--line);border-radius:12px;background:white;color:var(--text);box-shadow:0 10px 32px #182a3026;overflow-wrap:anywhere}
main{padding:36px 40px 64px;max-width:1240px;width:100%}.solo{max-width:520px;margin:10vh auto;padding:0 20px}
h1{font-size:28px;letter-spacing:-.03em;line-height:1.15;margin:4px 0 6px}h2{font-size:17px;margin:0 0 4px}h3{font-size:15px;margin:18px 0 8px}p{margin:0 0 12px}a{color:var(--brand)}
.page-head{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;flex-wrap:wrap;margin-bottom:24px}.page-head p{margin:0;color:var(--muted);max-width:64ch}.page-head .title{display:flex;align-items:center;gap:12px;flex-wrap:wrap}
.eyebrow{text-transform:uppercase;letter-spacing:.12em;font-size:11px;font-weight:750;color:#6f7f75}.crumbs{font-size:13px;color:var(--muted);margin-bottom:10px}.crumbs a{color:var(--brand);text-decoration:none}.crumbs a:hover{text-decoration:underline}
.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.btn,button{display:inline-flex;align-items:center;gap:6px;background:var(--brand);color:white;border:0;border-radius:9px;padding:9px 15px;font:inherit;font-size:14px;font-weight:650;text-decoration:none;cursor:pointer;line-height:1.25;white-space:nowrap}.btn:hover,button:hover{background:#27503d}
.btn.secondary,button.secondary{background:var(--brand-soft);color:#2b4d3b}.btn.secondary:hover,button.secondary:hover{background:#d9e6d8}.btn.ghost,button.ghost{background:transparent;color:var(--brand);border:1px solid var(--line)}.btn.ghost:hover,button.ghost:hover{background:#f1f5ef}
.btn.danger,button.danger{background:transparent;color:var(--danger);border:1px solid #ead2ca}.btn.danger:hover,button.danger:hover{background:var(--danger-bg)}.btn.sm,button.sm{padding:6px 10px;font-size:13px;border-radius:7px}
.card{background:var(--card);border:1px solid var(--line);border-radius:var(--radius);padding:22px;margin-bottom:20px}.card>p.lede{margin:0 0 16px;color:var(--muted);font-size:14px}.card-head{display:flex;justify-content:space-between;align-items:baseline;gap:12px;flex-wrap:wrap;margin-bottom:14px}.card-head h2,.card-head h3{margin:0}
.table-card{padding:0;overflow-x:auto}.card .table-card{margin:0 0 4px}table{width:100%;border-collapse:collapse;text-align:left;font-size:14px}th{font-size:11px;color:#6d796f;text-transform:uppercase;letter-spacing:.08em;background:#fafbf9;font-weight:700}td,th{padding:12px 18px;border-bottom:1px solid var(--line-soft);vertical-align:middle}tbody tr:last-child td{border-bottom:0}tbody tr:hover td{background:#fbfcfa}
td .name{font-weight:600;color:var(--text);text-decoration:none}td .name:hover{text-decoration:underline}small,.muted{color:var(--muted);font-size:13px}td small{display:block;margin-top:2px}td.num{text-align:right;font-variant-numeric:tabular-nums}td.right,th.right{text-align:right;white-space:nowrap}td.check-cell{width:32px;padding-right:0}
.pill{display:inline-block;border-radius:20px;padding:2px 9px;font-size:12px;font-weight:600;background:var(--off-bg);color:var(--off);white-space:nowrap}.pill.ok{background:var(--ok-bg);color:var(--ok)}.pill.info{background:var(--info-bg);color:var(--info)}.pill.warn{background:var(--warn-bg);color:var(--warn)}.pill.off{background:var(--off-bg);color:var(--off)}.pill.neutral{background:#eef1ec;color:#4c5a51}
.chips{display:flex;flex-wrap:wrap;gap:6px}.chip{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--line);background:#f8faf7;border-radius:8px;padding:3px 9px;font-size:13px;color:var(--text);text-decoration:none;max-width:100%;white-space:nowrap}.chip:hover{border-color:#b8c6b7;background:#f1f5ef}.chip span{color:var(--muted);font-size:12px}
.notice{background:var(--ok-bg);border:1px solid #c5dcc0;border-radius:10px;padding:12px 16px;margin-bottom:18px;color:var(--ok);font-size:14px}.notice.error{background:var(--danger-bg);border-color:#ebc2b2;color:var(--danger)}.notice.info{background:var(--info-bg);border-color:#c7d4ea;color:var(--info)}.notice.warn{background:var(--warn-bg);border-color:#ead9b7;color:var(--warn)}
.filters{display:flex;gap:12px;align-items:flex-end;flex-wrap:wrap;padding:16px 18px}.filters .grow{flex:1;min-width:220px}.filters label{font-size:12px;font-weight:600;color:var(--muted);display:block;margin-bottom:5px}.filters a{font-size:14px;align-self:center;padding-top:18px}
input,select{font:inherit;border:1px solid #c8d2c7;border-radius:8px;background:white;padding:8px 11px;color:inherit;max-width:100%;font-size:14px}input:disabled,select:disabled{background:#f2f4ef;color:var(--muted)}input[readonly]{background:#f2f4ef}input[type=text],input[type=email],input[type=search],input[type=url]{width:100%}input[type=checkbox]{width:16px;height:16px;accent-color:var(--brand);margin:0}
.field{margin-bottom:16px}.field label{display:block;font-size:14px;font-weight:600;margin-bottom:6px}.field small{display:block;margin-top:5px}.row{display:flex;gap:10px;align-items:flex-end;flex-wrap:wrap}.row .field{margin:0;flex:1;min-width:140px}.row .field.fixed{flex:0 0 auto}.inline{display:inline-flex;gap:8px;align-items:center;flex-wrap:wrap}form.inline{margin:0}
.split{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.15fr);gap:20px;align-items:start}.split.even{grid-template-columns:1fr 1fr}.split.wide{grid-template-columns:minmax(0,1.7fr) minmax(0,1fr)}.card .table-card td,.card .table-card th{padding:10px 12px}td.right .inline{justify-content:flex-end;flex-wrap:nowrap}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px;margin-bottom:20px}.stat{background:white;border:1px solid var(--line);border-radius:var(--radius);padding:18px 20px;text-decoration:none;color:inherit;display:block}.stat strong{font-size:28px;display:block;letter-spacing:-.03em;line-height:1.1}.stat span{color:var(--muted);font-size:13px}.stat:hover{border-color:#b8c6b7}
.check{display:flex;align-items:center;gap:10px;padding:7px 0;font-weight:450}fieldset{border:0;padding:0;margin:0 0 20px;min-width:0}legend{font-weight:700;margin-bottom:6px}
.empty{text-align:center;padding:36px 20px;color:var(--muted)}.empty h3{margin:0 0 6px;color:var(--text);font-size:16px}.pager{display:flex;justify-content:space-between;align-items:center;font-size:14px;color:var(--muted);margin-top:-8px}.pager .actions{gap:16px}
details.panel{border:1px solid var(--line);border-radius:10px;margin-top:14px;background:#fbfcfa}details.panel summary{cursor:pointer;padding:12px 16px;font-weight:600;font-size:14px}details.panel .body{padding:0 16px 16px}details.panel .body .table-card{background:white}
details.row-edit summary{cursor:pointer;font-size:13px;color:var(--brand);list-style:none;display:inline}details.row-edit summary::-webkit-details-marker{display:none}details.row-edit .body{margin-top:10px;padding:12px;border:1px solid var(--line);border-radius:8px;background:#fbfcfa}
ul.plain{list-style:none;padding:0;margin:0}.attention li{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:10px 0;border-bottom:1px solid var(--line-soft);font-size:14px}.attention li:last-child{border-bottom:0}.attention .count{font-weight:700;min-width:28px;text-align:right;font-variant-numeric:tabular-nums}
.candidates li{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:6px 12px;align-items:center;padding:12px 0;border-bottom:1px solid var(--line-soft);font-size:14px}.candidates li:last-child{border-bottom:0}.candidates .who{min-width:0}.candidates .who small{display:block}.candidates .chips{grid-column:1 / -1}.candidates label.check{padding:0;min-width:0}.candidates label.check>span{min-width:0}.candidates label.check small{display:block}
.people li{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:9px 0;border-bottom:1px solid var(--line-soft);font-size:14px}.people li:last-child{border-bottom:0}.people li>span:first-child{display:flex;flex-direction:column;min-width:0}.people li small{display:block}
.kv{display:grid;grid-template-columns:auto 1fr;gap:6px 18px;font-size:14px;margin:12px 0 0}.kv dt{color:var(--muted)}.kv dd{margin:0}pre.card{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}ol.steps li{margin-bottom:8px}
.graph{display:flex;flex-direction:column;align-items:center;padding:6px 0 2px}.graph-tier{width:100%;display:flex;flex-direction:column;align-items:center;gap:8px}.graph-tier-label{font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted);font-weight:700}.graph-nodes{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;width:100%}
.graph-node{display:flex;flex-direction:column;gap:2px;border:1px solid var(--line);border-left-width:3px;border-radius:10px;padding:9px 14px;background:#f8faf7;text-decoration:none;color:var(--text);min-width:150px;max-width:240px;font-size:14px;font-weight:600;line-height:1.3;overflow-wrap:anywhere}.graph-node small{font-weight:400;font-size:12px}a.graph-node:hover{border-color:#a9bba8;background:#f1f5ef}
.graph-node.adult{border-left-color:var(--info)}.graph-node.student{border-left-color:var(--ok)}.graph-node.family{border-left-color:var(--accent)}.graph-node.class{border-left-color:#7a5a9a}.graph-node.focus{background:var(--brand);border-color:var(--brand);color:white;min-width:190px;padding:12px 18px;font-size:15px}.graph-node.focus small{color:#d6e2d4}.graph-node.empty{border-style:dashed;background:transparent;color:var(--muted);font-weight:500}.graph-node.dim{opacity:.6}
.graph-edge{display:flex;flex-direction:column;align-items:center;font-size:12px;color:var(--muted);line-height:1}.graph-edge::before,.graph-edge::after{content:"";display:block;width:2px;height:14px;background:#c8d2c7}.graph-edge span{padding:3px 8px;border:1px solid var(--line-soft);border-radius:12px;background:white}
:focus-visible{outline:3px solid var(--accent);outline-offset:2px}
@media(max-width:1180px){.split.wide{grid-template-columns:1fr}}
@media(max-width:900px){.shell{grid-template-columns:1fr}.sidebar{position:static;height:auto;flex-direction:row;flex-wrap:wrap;align-items:center;padding:14px 16px;gap:8px}.sidebar nav{flex-direction:row;flex-wrap:wrap}.sidebar .group{display:none}.sidebar-foot{margin:0 0 0 auto;flex-direction:row;align-items:center}.sidebar-foot button{width:auto}.account-details{left:auto;right:0;bottom:auto;top:calc(100% + 8px)}main{padding:24px 16px 48px}.split,.split.even{grid-template-columns:1fr}td,th{padding:10px 12px}h1{font-size:24px;overflow-wrap:anywhere}}`;
/** Language switcher; posts to /admin/lang and returns to the current page. */
export function languageSwitch() {
  const current = currentLocale();
  return `<form class="lang-switch" method="post" action="/admin/lang" aria-label="${e(t("Language"))}">${hidden("returnTo", currentPath())}${locales.map(l => `<button name="lang" value="${l}" ${l === current ? 'aria-current="true" disabled' : ""} lang="${l}">${localeNames[l]}</button>`).join("")}</form>`;
}
export function layout(title: string, content: string, showNavigation = true, active?: NavKey) {
  const nav = navigation.map(section => `<div class="group">${e(t(section.group))}</div>${section.items.map(([key, href, label]) => `<a href="${href}" ${active === key ? 'aria-current="page"' : ""}>${e(t(label))}</a>`).join("")}`).join("");
  const body = showNavigation
    ? `<div class="shell"><aside class="sidebar"><a class="brand" href="/admin">SMZ <span>/ Identity</span></a><nav aria-label="${e(t("Administration"))}">${nav}</nav><div class="sidebar-foot"><!--signed-in-account-->${languageSwitch()}<form method="post" action="/admin/sign-out"><button type="submit" class="secondary">${e(t("Sign out"))}</button></form></div></aside><main>${content}</main></div>`
    : `<main class="solo">${languageSwitch()}${content}</main>`;
  return `<!doctype html><html lang="${currentLocale()}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · SMZ Identity</title><style>${css}</style></head><body>${body}</body></html>`;
}
// ---- Shared building blocks -------------------------------------------------
export const hidden = (name: string, value: string) => `<input type="hidden" name="${e(name)}" value="${e(value)}">`;
export const notice = (text: string, tone: "ok" | "error" | "info" | "warn" = "ok") => `<div class="notice ${tone}" role="${tone === "error" ? "alert" : "status"}">${e(text)}</div>`;
export const pill = (label: string, tone: "ok" | "info" | "warn" | "off" | "neutral" = "neutral") => `<span class="pill ${tone}">${e(label)}</span>`;
export const statusPill = (status: string) => pill(status === "active" ? t("Active") : status === "disabled" ? t("Disabled") : status, status === "active" ? "ok" : "off");
const stateLabels: Record<MembershipState, [string, "ok" | "info" | "off"]> = { active: ["Active", "ok"], scheduled: ["Scheduled", "info"], ended: ["Ended", "off"], inactive: ["Inactive", "off"] };
export const statePill = (state: MembershipState) => pill(t(stateLabels[state][0]), stateLabels[state][1]);
export const relationshipLabel = label;
export const chip = (href: string, label: string, meta?: string) => `<a class="chip" href="${e(href)}">${e(label)}${meta ? ` <span>${e(meta)}</span>` : ""}</a>`;
export const chips = (items: string[], empty = "—") => items.length ? `<div class="chips">${items.join("")}</div>` : `<span class="muted">${e(empty)}</span>`;
export const personHref = (p: { id: string; kind: string }) => p.kind === "student" ? `/admin/students/${p.id}` : `/admin/users/${p.id}`;
export const personLink = (p: { id: string; kind: string; displayName: string }) => `<a class="name" href="${personHref(p)}">${e(p.displayName)}</a>`;
export const dateRange = (l: { startsOn: string | null; endsOn: string | null }) => l.startsOn || l.endsOn ? `${l.startsOn ?? "…"} → ${l.endsOn ?? "…"}` : t("No date bounds");
export const emptyState = (title: string, body: string) => `<div class="empty"><h3>${e(title)}</h3>${body}</div>`;
export const crumbs = (items: [string, string?][]) => `<div class="crumbs">${items.map(([label, href]) => href ? `<a href="${e(href)}">${e(label)}</a>` : `<span>${e(label)}</span>`).join(" › ")}</div>`;
export function pageHead(o: { eyebrow?: string; title: string; titleExtra?: string; lede?: string; actions?: string; crumbs?: [string, string?][] }) {
  return `${o.crumbs ? crumbs(o.crumbs) : ""}<header class="page-head"><div>${o.eyebrow ? `<span class="eyebrow">${e(o.eyebrow)}</span>` : ""}<div class="title"><h1>${e(o.title)}</h1>${o.titleExtra ?? ""}</div>${o.lede ? `<p>${o.lede}</p>` : ""}</div>${o.actions ? `<div class="actions">${o.actions}</div>` : ""}</header>`;
}
const nouns: Record<string, [string, string]> = { person: ["{n} person", "{n} people"], student: ["{n} student", "{n} students"], family: ["{n} family", "{n} families"], class: ["{n} class", "{n} classes"] };
export function pager(total: number, page: number, pages: number, link: (p: number) => string, noun: string) {
  const [one, many] = nouns[noun] ?? [`{n} ${noun}`, `{n} ${noun}s`];
  return `<div class="pager"><span>${e(tn(total, one, many))} · ${e(t("Page {page} of {pages}", { page, pages }))}</span><div class="actions">${page > 1 ? `<a href="${e(link(page - 1))}">← ${e(t("Previous"))}</a>` : ""}${page < pages ? `<a href="${e(link(page + 1))}">${e(t("Next"))} →</a>` : ""}</div></div>`;
}
// ---- Relationship graph -----------------------------------------------------------
export type GraphNode = { title: string; meta?: string; href?: string; kind: "focus" | "adult" | "student" | "family" | "class" | "empty"; dim?: boolean };
export type GraphTier = { label?: string; edge?: string; nodes: GraphNode[] };
const graphLimit = 24;
/** CSS-only tiered graph: the focus entity in the middle, direct relations above/below, second-degree relations on the outer tiers. */
export function relationshipGraph(tiers: GraphTier[], label: string) {
  const node = (n: GraphNode) => {
    const body = `${e(n.title)}${n.meta ? `<small>${e(n.meta)}</small>` : ""}`;
    const cls = `graph-node ${n.kind}${n.dim ? " dim" : ""}`;
    return n.href ? `<a class="${cls}" href="${e(n.href)}">${body}</a>` : `<div class="${cls}">${body}</div>`;
  };
  const tier = (tr: GraphTier, i: number) => {
    const shown = tr.nodes.slice(0, graphLimit), extra = tr.nodes.length - shown.length;
    return `${i > 0 && tr.edge ? `<div class="graph-edge" aria-hidden="true"><span>${e(tr.edge)}</span></div>` : ""}<div class="graph-tier">${tr.label ? `<div class="graph-tier-label">${e(tr.label)}</div>` : ""}<div class="graph-nodes">${shown.map(node).join("")}${extra > 0 ? node({ title: t("+{n} more", { n: extra }), kind: "empty" }) : ""}</div></div>`;
  };
  return `<section class="graph" role="group" aria-label="${e(label)}">${tiers.map(tier).join("")}</section>`;
}
export const graphEmpty = (title: string, href?: string): GraphNode => ({ title, kind: "empty", href });
/** Stacked list of add-candidates that stays usable in narrow columns: heading + meta, optional chips, trailing action. */
export const candidateList = (items: { head: string; meta?: string; chips?: string; action: string }[]) =>
  `<ul class="plain candidates">${items.map(i => `<li><div class="who">${i.head}${i.meta ? `<small>${i.meta}</small>` : ""}</div><div>${i.action}</div>${i.chips ? `<div class="chips">${i.chips}</div>` : ""}</li>`).join("")}</ul>`;
export const selectOptions = (options: [string, string][], selected: string) => options.map(([value, label]) => `<option value="${e(value)}" ${value === selected ? "selected" : ""}>${e(label)}</option>`).join("");
// ---- Overview ---------------------------------------------------------------
export function dashboardView(insights: Insights, extra: { pendingInvitations: number; applications: number }) {
  const a = insights.attention;
  const items: [number, string, string, string][] = [
    [a.studentsWithoutClass.length, t("Students not enrolled in any class"), "/admin/students?needs=class", t("Enroll")],
    [a.studentsWithoutFamily.length, t("Students without a family"), "/admin/students?needs=family", t("Connect")],
    [a.familiesWithoutGuardian.length, t("Families without an active parent or guardian"), "/admin/families?needs=guardian", t("Review")],
    [a.familiesWithoutChildren.length, t("Families without children"), "/admin/families?needs=children", t("Review")],
    [a.classesWithoutTeacher.length, t("Classes without a teacher"), "/admin/classes?needs=teacher", t("Assign")],
    [a.parentsWithoutFamily.length, t("Parents not linked to a family"), "/admin/users?role=parent&kind=adult", t("Review")],
  ];
  const open = items.filter(i => i[0] > 0);
  const stats: [string, number, string][] = [[t("Adults"), insights.counts.adults, "/admin/users?kind=adult"], [t("Students"), insights.counts.students, "/admin/students"], [t("Families"), insights.counts.families, "/admin/families"], [t("Classes"), insights.counts.classes, "/admin/classes"], [t("Applications"), extra.applications, "/admin/applications"], [t("Awaiting first sign-in"), extra.pendingInvitations, "/admin/users?kind=adult"]];
  const quick: [string, string, string, string, string][] = [
    [t("Set up a new family"), t("Student, class, parents and family in one guided flow."), "/admin/families/wizard", t("Start"), "btn sm"],
    [t("Pre-approve an adult"), t("Teacher, parent or administrator login account."), "/admin/users/new", t("Add user"), "btn secondary sm"],
    [t("Add a student"), t("Directory record without a login."), "/admin/students/new", t("Add student"), "btn secondary sm"],
    [t("Create a class"), t("Use the same class code as the CMS."), "/admin/classes/new", t("Add class"), "btn secondary sm"],
    [t("Register an application"), t("OIDC client with PKCE and directory access."), "/admin/applications/new", t("Register"), "btn secondary sm"],
  ];
  return layout(t("Overview"), `${pageHead({ eyebrow: t("Administration"), title: t("Overview"), lede: e(t("The school directory at a glance. Start from a person, family or class — relationships can be managed from either side.")), actions: `<a class="btn" href="/admin/families/wizard">${e(t("New family setup"))}</a><a class="btn secondary" href="/admin/users/new">${e(t("Add user"))}</a>` })}
<div class="stats">${stats.map(([label, count, href]) => `<a class="stat" href="${href}"><strong>${count}</strong><span>${e(label)}</span></a>`).join("")}</div>
<div class="split even"><section class="card"><div class="card-head"><h2>${e(t("Needs attention"))}</h2>${open.length ? pill(t("{n} open", { n: open.reduce((n, i) => n + i[0], 0) }), "warn") : pill(t("All connected"), "ok")}</div><p class="lede">${e(t("Relationship gaps that affect who can see what in connected applications."))}</p>${open.length ? `<ul class="plain attention">${open.map(([count, label, href, action]) => `<li><span class="count">${count}</span><span style="flex:1">${e(label)}</span><a class="btn ghost sm" href="${href}">${e(action)} →</a></li>`).join("")}</ul>` : `<p class="muted">${e(t("Every active student has a class and a family, every family has a guardian and children, and every class has a teacher."))}</p>`}</section>
<section class="card"><h2>${e(t("Quick actions"))}</h2><p class="lede">${e(t("Common tasks. Nothing here sends email."))}</p><ul class="plain people">${quick.map(([title, desc, href, action, cls]) => `<li><span><strong>${e(title)}</strong><small>${e(desc)}</small></span><a class="${cls}" href="${href}">${e(action)}</a></li>`).join("")}</ul></section></div>`, true, "overview");
}
// ---- Users ------------------------------------------------------------------
export type UserFilters = { q: string; status: string; role: string; kind: string; page: number };
export function usersListView(data: Awaited<ReturnType<Service["list"]>>, f: UserFilters) {
  const link = (p: number) => `/admin/users?${new URLSearchParams({ q: f.q, status: f.status, role: f.role, kind: f.kind, page: String(p) })}`;
  const pages = Math.max(1, Math.ceil(data.total / 25));
  const relationships = (p: (typeof data.rows)[number]) => chips([
    ...p.families.map(x => chip(`/admin/families/${x.id}`, x.name, relationshipLabel(x.relationship))),
    ...p.classes.map(x => chip(`/admin/classes/${x.id}`, x.name, relationshipLabel(x.relationship))),
  ], p.kind === "student" ? t("Not assigned") : "—");
  return layout(t("Users"), `${pageHead({ eyebrow: t("Directory"), title: t("Users"), lede: e(t("Every person in the directory. Adults sign in; students are records only. Open a person to manage their roles and relationships.")), actions: `<a class="btn" href="/admin/users/new">+ ${e(t("Add adult"))}</a><a class="btn secondary" href="/admin/students/new">+ ${e(t("Add student"))}</a>` })}
<form class="card filters" method="get" action="/admin/users"><div class="grow"><label for="q">${e(t("Search"))}</label><input id="q" name="q" type="search" placeholder="${e(t("Name or email"))}" value="${e(f.q)}" maxlength="120"></div><div><label for="kind">${e(t("Kind"))}</label><select id="kind" name="kind">${selectOptions([["", t("Adults and students")], ["adult", t("Adults")], ["student", t("Students")]], f.kind)}</select></div><div><label for="role">${e(t("Role"))}</label><select id="role" name="role">${selectOptions([["", t("Any role")], ["admin", t("Admin")], ["teacher", t("Teacher")], ["parent", t("Parent")], ["student", t("Student")]], f.role)}</select></div><div><label for="status">${e(t("Status"))}</label><select id="status" name="status">${selectOptions([["", t("Any status")], ["active", t("Active")], ["disabled", t("Disabled")]], f.status)}</select></div><button>${e(t("Apply"))}</button><a href="/admin/users">${e(t("Reset"))}</a></form>
<div class="card table-card">${data.rows.length ? `<table><thead><tr><th scope="col">${e(t("Person"))}</th><th scope="col">${e(t("Roles"))}</th><th scope="col">${e(t("Relationships"))}</th><th scope="col">${e(t("Status"))}</th></tr></thead><tbody>${data.rows.map(p => `<tr><td>${personLink(p)}<small>${e(p.normalizedLoginEmail || t("Student · no login"))}</small></td><td>${p.roles.length ? p.roles.map(r => pill(relationshipLabel(r), r === "admin" ? "info" : "neutral")).join(" ") : `<span class="muted">${e(t("No roles"))}</span>`}</td><td>${relationships(p)}</td><td>${statusPill(p.status)}${p.kind === "adult" && p.invitation === "pending" && p.status === "active" ? ` ${pill(t("Awaiting sign-in"), "warn")}` : ""}</td></tr>`).join("")}</tbody></table>` : emptyState(t("No people found"), `<p>${e(t("Try another search, reset the filters, or add a new user."))}</p>`)}</div>${pager(data.total, f.page, pages, link, "person")}`, true, "users");
}
type Person = NonNullable<Awaited<ReturnType<Service["detail"]>>>;
export type EditOptions = { error?: string; saved?: boolean; signedOut?: boolean; readOnly?: boolean; values?: Record<string, unknown>; returnTo?: string; addQuery?: string };
export function editView(person: Person | null, options: EditOptions = {}, ctx?: PersonContext) {
  const v = options.values ?? {};
  const value = (key: "displayName" | "email" | "status", fallback: string | null | undefined) => e(typeof v[key] === "string" ? v[key] : fallback ?? "");
  const roles = Array.isArray(v.roles) ? (v.roles as string[]) : person?.roles ?? [];
  const title = person ? person.displayName : t("Add adult account");
  const creating = !person;
  const roleHints: Record<string, string> = { teacher: t("can be assigned to classes"), parent: t("can be added to families"), admin: t("manages this directory") };
  const formCard = `<form method="post" action="${person ? `/admin/users/${person.id}` : "/admin/users"}"><fieldset ${options.readOnly ? "disabled" : ""}>${hidden("version", person?.updatedAt.toISOString() || "")}${options.returnTo ? hidden("returnTo", options.returnTo) : ""}<section class="card"><h2>${e(t("Identity"))}</h2><p class="lede">${e(creating ? t("Pre-approve an adult to sign in with their existing email address. No email is sent.") : t("Login email is fixed to preserve the linked sign-in identity."))}</p><div class="field"><label for="displayName">${e(t("Full name"))}</label><input type="text" id="displayName" name="displayName" value="${value("displayName", person?.displayName)}" required maxlength="120" autocomplete="name"></div><div class="field"><label for="email">${e(t("Login email"))}</label><input type="email" id="email" name="email" value="${value("email", person?.normalizedLoginEmail)}" required maxlength="254" autocomplete="email" ${person ? "readonly" : ""}>${creating ? `<small>${e(t("Use the exact email the school has approved."))}</small>` : ""}</div><div class="field"><label for="accountStatus">${e(t("Account status"))}</label><select id="accountStatus" name="status">${selectOptions([["active", t("Active")], ["disabled", t("Disabled")]], String(v.status ?? person?.status ?? "active"))}</select><small>${e(t("Disabling immediately revokes all sessions and blocks sign-in and application access."))}</small></div><fieldset><legend>${e(t("School roles"))}</legend>${["admin", "teacher", "parent"].map(role => `<label class="check"><input type="checkbox" name="roles" value="${role}" ${roles.includes(role) ? "checked" : ""}>${e(relationshipLabel(role))} <small>· ${e(roleHints[role]!)}</small></label>`).join("")}</fieldset>${!options.readOnly ? `<div class="actions"><button type="submit">${e(creating ? t("Create account") : t("Save changes"))}</button><a class="btn ghost" href="${e(options.returnTo || "/admin/users")}">${e(t("Cancel"))}</a></div>${person ? `<p class="muted" style="margin-top:12px">${e(t("Saving signs this user out of their current sessions. You cannot remove your own administrator access."))}</p>` : ""}` : ""}</section></fieldset></form>`;
  const invitationPill = person?.invitation ? pill(person.invitation.status === "activated" ? t("Signed in before") : t("Invitation {status}", { status: t(person.invitation.status) }), person.invitation.status === "activated" ? "ok" : person.invitation.status === "pending" ? "warn" : "off") : "";
  const sessions = person?.kind === "adult" && person.normalizedLoginEmail ? `<section class="card"><div class="card-head"><h2>${e(t("Sessions"))}</h2>${invitationPill}</div><p class="lede">${e(t("End every current session without disabling the account. The user can sign in again."))}</p><form method="post" action="/admin/users/${person.id}/sign-out"><button type="submit" class="ghost">${e(t("Force sign out"))}</button></form></section>` : "";
  const graph = person && ctx ? `<section class="card"><div class="card-head"><h2>${e(t("Relationship graph"))}</h2><span class="muted">${e(t("Click a node to open it"))}</span></div>${adultGraph(person, ctx)}</section>` : "";
  const relationships = person && ctx ? adultRelationships(person, ctx, options) : creating ? `<section class="card"><h2>${e(t("Relationships"))}</h2><p class="lede">${e(t("After the account is created you can add this adult to families as a parent or guardian, or assign them to classes as a teacher."))}</p>${options.returnTo ? `<p class="muted">${t("You will return to {link} to finish linking.", { link: `<a href="${e(options.returnTo)}">${e(t("where you started"))}</a>` })}</p>` : ""}</section>` : "";
  return layout(title, `${pageHead({ crumbs: [[t("Users"), "/admin/users"], [title]], eyebrow: creating ? t("New adult account") : t("Adult account"), title, titleExtra: person ? statusPill(person.status) : "", lede: person ? e(person.normalizedLoginEmail || t("No login email")) : undefined })}
${options.signedOut ? notice(t("User signed out from all sessions. They can sign in again if their account is active.")) : ""}${options.saved ? notice(t("User saved.")) : ""}${options.error ? notice(options.error, "error") : ""}${options.readOnly ? notice(t("This record is read-only. Synthetic development identities are managed by the directory seeder."), "info") : ""}
${graph}<div class="split">${formCard}<div>${relationships}${sessions}</div></div>`, true, "users");
}
function adultGraph(person: Person, ctx: PersonContext) {
  const live = (s: string) => s === "active" || s === "scheduled";
  const families = ctx.familyLinks.filter(l => live(l.state));
  const classes = ctx.classLinks.filter(l => live(l.state));
  const children = ctx.related.filter(r => r.relationship === "child");
  const scheduled = (state: string) => state === "scheduled" ? ` · ${t("scheduled")}` : "";
  const tiers: GraphTier[] = [
    { label: t("Families"), nodes: families.length ? families.map(l => ({ title: l.group.displayName, meta: `${relationshipLabel(l.relationship)}${scheduled(l.state)}`, href: `/admin/families/${l.group.id}`, kind: "family", dim: l.state !== "active" })) : [graphEmpty(ctx.roles.includes("parent") ? t("Not in any family yet") : t("No families"))] },
    { edge: t("parent or guardian"), nodes: [{ title: person.displayName, meta: ctx.roles.map(relationshipLabel).join(", ") || t("No roles"), kind: "focus" }] },
  ];
  if (ctx.isTeacher || classes.length) tiers.push({ edge: t("teaches"), label: t("Classes"), nodes: classes.length ? classes.map(l => ({ title: l.group.displayName, meta: tn(l.studentCount, "{n} student", "{n} students"), href: `/admin/classes/${l.group.id}`, kind: "class", dim: l.state !== "active" })) : [graphEmpty(t("No classes assigned"))] });
  if (families.length) tiers.push({ edge: t("children"), label: t("Children"), nodes: children.length ? children.map(r => ({ title: r.person.displayName, meta: `${r.family.displayName} · ${r.summary.classes.length ? r.summary.classes.map(c => c.name).join(", ") : t("not enrolled")}`, href: personHref(r.person), kind: "student" })) : [graphEmpty(t("No children in these families"))] });
  return relationshipGraph(tiers, t("Relationships of {name}", { name: person.displayName }));
}
function adultRelationships(person: Person, ctx: PersonContext, options: EditOptions) {
  const here = `/admin/users/${person.id}`;
  const manage = !options.readOnly;
  const form = (kind: string, extra: Record<string, string>, body: string, cls = "inline") => `<form class="${cls}" method="post" action="/admin/directory/save">${hidden("kind", kind)}${hidden("version", ctx.version)}${hidden("returnTo", here)}${Object.entries(extra).map(([k, val]) => hidden(k, val)).join("")}${body}</form>`;
  const endButton = (id: string, label: string) => manage ? form("end-memberships", { membershipIds: id }, `<button class="danger sm" aria-label="${e(label)}">${e(t("End"))}</button>`) : "";
  const familyRows = ctx.familyLinks.map(l => `<tr><td><a class="name" href="/admin/families/${l.group.id}">${e(l.group.displayName)}</a><small>${e(l.group.code)}</small></td><td>${e(relationshipLabel(l.relationship))}</td><td>${statePill(l.state)}<small>${e(dateRange(l))}</small></td><td class="right">${l.state === "active" || l.state === "scheduled" ? endButton(l.id, t("End {name}'s membership in {group}", { name: person.displayName, group: l.group.displayName })) : ""}</td></tr>`).join("");
  const classRows = ctx.classLinks.map(l => `<tr><td><a class="name" href="/admin/classes/${l.group.id}">${e(l.group.displayName)}</a><small>${e(l.group.code)}</small></td><td>${e(relationshipLabel(l.relationship))}</td><td>${statePill(l.state)}<small>${e(dateRange(l))}</small></td><td class="right">${l.state === "active" || l.state === "scheduled" ? endButton(l.id, t("End {name}'s assignment to {group}", { name: person.displayName, group: l.group.displayName })) : ""}</td></tr>`).join("");
  const q = options.addQuery ?? "";
  const relationshipOptions: [string, string][] = [["mother", t("Mother")], ["father", t("Father")], ["guardian", t("Guardian")]];
  const addFamily = manage ? `<details class="panel" ${q ? "open" : ""}><summary>${e(t("Add to a family"))}</summary><div class="body"><form class="row" method="get" action="${here}"><div class="field"><label for="add">${e(t("Find a family"))}</label><input id="add" name="add" type="search" value="${e(q)}" placeholder="${e(t("Family name or code"))}" maxlength="120"></div><div class="field fixed"><button class="secondary">${e(t("Search"))}</button></div></form>${q ? ctx.familyMatches.length ? candidateList(ctx.familyMatches.map(f => ({ head: `<a class="name" href="/admin/families/${f.id}">${e(f.displayName)}</a>`, meta: `${e(f.code)} · ${e(f.members.join(", ") || t("No members yet"))}`, action: form("family-member", { groupId: f.id, personIds: person.id, status: "active" }, `<select name="relationship" aria-label="${e(t("Relationship in {group}", { group: f.displayName }))}">${selectOptions(relationshipOptions, "guardian")}</select><button class="sm">${e(t("Add"))}</button>`) }))) : `<p class="muted" style="margin-top:12px">${e(t("No active family matches “{q}”.", { q }))} <a href="/admin/families/new">${e(t("Create a family"))}</a>.</p>` : `<p class="muted" style="margin-top:10px">${e(t("Search for an existing family, or"))} <a href="/admin/families/new">${e(t("create a new family"))}</a>.</p>`}</div></details>` : "";
  const assignClass = manage ? ctx.isTeacher ? ctx.classOptions.length ? `<details class="panel"><summary>${e(t("Assign to a class as teacher"))}</summary><div class="body">${form("class-member", { personIds: person.id, relationship: "teacher", status: "active" }, `<div class="row"><div class="field"><label for="classId">${e(t("Class"))}</label><select id="classId" name="groupId" required><option value="">${e(t("Choose a class"))}</option>${ctx.classOptions.map(c => `<option value="${c.id}">${e(c.displayName)} (${e(c.code)})</option>`).join("")}</select></div><div class="field fixed"><label for="startsOn">${e(t("From"))}</label><input id="startsOn" type="date" name="startsOn"></div><div class="field fixed"><button>${e(t("Assign"))}</button></div></div>`, "")}</div></details>` : `<p class="muted">${e(t("Already assigned to every active class."))}</p>` : `<p class="muted">${t("Add the {role} role and save to assign classes.", { role: `<strong>${e(t("Teacher"))}</strong>` })}</p>` : "";
  const children = ctx.related.filter(r => r.relationship === "child");
  const coParents = ctx.related.filter(r => r.relationship !== "child");
  return `<section class="card"><div class="card-head"><h2>${e(t("Families"))}</h2>${ctx.familyLinks.some(l => l.state === "active") ? pill(t("{n} active", { n: ctx.familyLinks.filter(l => l.state === "active").length }), "ok") : pill(t("None"), "neutral")}</div><p class="lede">${e(t("Parents see their children's classes in connected applications through these memberships."))}</p>${familyRows ? `<div class="table-card card"><table><thead><tr><th>${e(t("Family"))}</th><th>${e(t("Relationship"))}</th><th>${e(t("Status"))}</th><th></th></tr></thead><tbody>${familyRows}</tbody></table></div>` : `<p class="muted">${e(t("Not a member of any family."))}</p>`}${addFamily}${children.length ? `<h3>${e(t("Children"))}</h3><ul class="plain people">${children.map(r => `<li><span>${personLink(r.person)}<small>${e(t("via {family}", { family: r.family.displayName }))}</small></span>${statusPill(r.person.status)}</li>`).join("")}</ul>` : ""}${coParents.length ? `<h3>${e(t("Other parents and guardians"))}</h3><ul class="plain people">${coParents.map(r => `<li><span>${personLink(r.person)}<small>${e(relationshipLabel(r.relationship))} · ${e(r.family.displayName)}</small></span></li>`).join("")}</ul>` : ""}</section>
<section class="card"><div class="card-head"><h2>${e(t("Classes"))}</h2>${ctx.isTeacher ? pill(t("Teacher"), "info") : ""}</div><p class="lede">${e(t("Teachers see their classes in connected applications through these assignments."))}</p>${classRows ? `<div class="table-card card"><table><thead><tr><th>${e(t("Class"))}</th><th>${e(t("Role"))}</th><th>${e(t("Status"))}</th><th></th></tr></thead><tbody>${classRows}</tbody></table></div>` : `<p class="muted">${e(t("Not assigned to any class."))}</p>`}${assignClass}</section>`;
}
