import { formatPhone, normalizePhone } from "./phone.js";
import { escape as e } from "../admin/views.js";

export const labels: Record<string, string> = {
  mailingAddress: "通訊地址", contactPhone: "聯絡電話", displayName: "姓名", contactEmail: "聯絡信箱",
};
export const states: Record<string, string> = {
  draft: "草稿", pending: "待審核", returned: "退回修改", approved: "已核准", rejected: "未核准", withdrawn: "已撤回",
};
export const fieldKeys = (kind: string) => kind === "person"
  ? ["displayName", "contactPhone", "contactEmail"] : ["mailingAddress", "contactPhone"];
export const hidden = (key: string, value: unknown) =>
  `<input type="hidden" name="${e(key)}" value="${e(String(value))}">`;
export const badge = (status: string) => `<span class="badge ${e(status)}">${e(states[status] ?? status)}</span>`;
export const displayValue = (key: string, value: string) =>
  (key === "contactPhone" ? formatPhone(value) : value) || "尚未提供";
export const sameValue = (key: string, left: string, right: string) =>
  key === "contactPhone" ? normalizePhone(left) === normalizePhone(right) : left === right;
export const values = (data: Record<string, string>, kind: string, keys = fieldKeys(kind)) =>
  `<dl class="values">${keys.map(k => `<div><dt>${labels[k]}</dt><dd${data[k] ? "" : ' class="muted"'}>${e(displayValue(k, data[k] ?? ""))}</dd></div>`).join("")}</dl>`;
export const timestamp = (value: unknown) => {
  const date = new Date(String(value));
  return Number.isNaN(date.getTime()) ? "時間未提供" : new Intl.DateTimeFormat("zh-TW", {
    timeZone: "Asia/Taipei", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false,
  }).format(date);
};
export const field = (key: string, value: string, kind: string, prefix = "") => {
  if (key === "contactPhone") value = normalizePhone(value);
  const required = key === "displayName";
  const hints: Record<string, string> = {
    mailingAddress: "請填寫完整地址，送出審核前必填。",
    contactPhone: kind === "family" ? "請填寫含區碼的電話；可輸入 - 或 ( )，顯示時會自動排版。送審前必填。" : "選填，可填寫手機或含區碼的市話；可輸入 - 或 ( )，顯示時會自動排版。",
    contactEmail: "選填，用於聯絡；不會變更您的登入信箱。",
    displayName: "請填寫學校聯絡時使用的姓名。",
  };
  const attrs = `id="field-${prefix}${key}" name="${key}" aria-describedby="hint-${prefix}${key}"`;
  const control = key === "mailingAddress"
    ? `<textarea ${attrs} rows="3" maxlength="500" autocomplete="street-address">${e(value)}</textarea>`
    : `<input ${attrs} type="${key === "contactEmail" ? "email" : key === "contactPhone" ? "tel" : "text"}" autocomplete="${key === "contactEmail" ? "email" : key === "contactPhone" ? "tel" : "name"}" value="${e(value)}" maxlength="${key === "displayName" ? 120 : key === "contactEmail" ? 254 : 40}" ${required ? "required" : ""}>`;
  return `<div class="field"><label for="field-${prefix}${key}">${labels[key]}${required ? ' <span class="required">必填</span>' : ""}</label>${control}<small id="hint-${prefix}${key}">${hints[key]}</small></div>`;
};

type FamilyGraphMember = { name: string; kind: string; relationship: string };
const relationshipNames: Record<string, string> = { father: "父親", mother: "母親", guardian: "監護人", child: "孩子" };

/** Only render the members already authorised by familyProfileService. No profile links. */
export function familyGraph(familyName: string, members: FamilyGraphMember[]) {
  const adults = members.filter(m => m.relationship !== "child" && m.kind === "adult");
  const children = members.filter(m => m.relationship === "child");
  const tier = (people: FamilyGraphMember[], kind: "adults" | "children") =>
    `<ul class="family-branches ${kind}" aria-label="${kind === "adults" ? "家長與監護人" : "孩子"}">${people.map(m => `<li><div class="family-node ${kind === "children" ? "child" : "adult"}"><span class="node-role">${e(relationshipNames[m.relationship] ?? m.relationship)}</span><strong>${e(m.name)}</strong></div></li>`).join("")}</ul>`;
  return `<section class="panel family-map" aria-labelledby="family-map-title"><div class="panel-head"><h2 id="family-map-title">家庭關係</h2><span class="badge">${children.length} 位孩子</span></div><p class="request-intro">家長、監護人與孩子在同一家庭中的連結。</p><div class="family-tree">${adults.length ? tier(adults, "adults") : '<p class="empty">目前沒有有效的家長或監護人連結。</p>'}<div class="family-hub ${adults.length ? "has-adults" : ""} ${children.length ? "has-children" : ""}"><div class="family-node household"><span class="node-role">家庭</span><strong>${e(familyName)}</strong></div></div>${children.length ? tier(children, "children") : '<p class="empty">目前尚未連結孩子。若需更新家庭關係，請聯絡學校。</p>'}</div><p class="panel-footer">顯示學校登記的現行家庭關係；關係變更請聯絡學校。</p></section>`;
}

const css = `
:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans TC",sans-serif;color:#243d32;background:#f4f6f3;font-size:16px;line-height:1.6;--green:#2e5844;--muted:#65746b;--line:#dce4dd}
*{box-sizing:border-box}body{margin:0}a{color:var(--green)}button,input,textarea{font:inherit}button,a,input,textarea,summary{-webkit-tap-highlight-color:transparent}:focus-visible{outline:3px solid #b68836;outline-offset:3px}
.topbar{background:#fff;border-bottom:1px solid var(--line)}.topbar-inner{max-width:1120px;margin:auto;padding:18px 32px;display:flex;justify-content:space-between;align-items:center;gap:16px}.brand{font-size:15px;font-weight:650;text-decoration:none;display:flex;align-items:center;gap:12px}.brand-mark{background:var(--green);color:white;border-radius:9px;padding:7px 10px;font-size:13px;letter-spacing:.07em}.app-link{font-size:14px;text-decoration:none;white-space:nowrap}.header-actions{display:flex;align-items:center;gap:24px;min-width:0}.signed-in-account{display:flex;align-items:center;gap:16px;min-width:0}.account-identity{display:grid;gap:2px;min-width:0;overflow-wrap:anywhere}.account-identity small,.account-identity span{font-size:12px;color:var(--muted)}.account-identity strong{font-size:14px}.signed-in-account form{margin:0;flex-shrink:0}.signed-in-account button{padding:8px 14px;white-space:nowrap}
main{max-width:1120px;padding:28px 32px 72px;margin:auto}.tabs{display:flex;gap:6px;border-bottom:1px solid var(--line);margin-bottom:30px}.tabs a{text-decoration:none;padding:10px 18px;border-bottom:3px solid transparent;color:var(--muted);font-weight:650}.tabs a[aria-current]{border-color:var(--green);color:var(--green)}.tabs a:hover{background:#eaf0e9}.page-head{margin-bottom:28px}.eyebrow{font-size:12px;color:var(--muted);letter-spacing:.1em;margin:0 0 8px}.page-head h1{font-size:30px;line-height:1.3;margin:0 0 10px;letter-spacing:-.03em}.page-head p{color:var(--muted);margin:0;max-width:65ch}
h2{font-size:19px;line-height:1.4;margin:0}h3{font-size:16px;margin:0 0 8px}p{margin:0 0 16px}small,.muted{color:var(--muted)}small{display:block;font-size:13px}.workspace{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.4fr);gap:24px;align-items:start}.stack{display:grid;gap:24px;min-width:0}.panel{background:white;border:1px solid var(--line);border-radius:16px;padding:26px;min-width:0}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:20px}.panel-head h2{min-width:0}.panel>p:last-child{margin-bottom:0}.panel-footer{border-top:1px solid var(--line);padding-top:16px;margin-top:20px;font-size:13px;color:var(--muted)}.badge{display:inline-block;flex-shrink:0;padding:4px 10px;border-radius:20px;font-size:12px;font-weight:650;background:#edf1ec;color:#4b6153}.badge.pending,.badge.returned{background:#fff1d8;color:#805a18}.badge.approved{background:#e6f2e7;color:#326340}.badge.rejected{background:#f9e9e4;color:#953d2b}.values{margin:0;display:grid;gap:18px}.values dt{color:var(--muted);font-size:13px;margin-bottom:3px}.values dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere;font-weight:500}.member{padding:18px 0;border-bottom:1px solid var(--line)}.member:first-of-type{padding-top:0}.member:last-child{border:0;padding-bottom:0}.member h3{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.member .values{gap:12px}.parent-editors{margin-top:28px}.parent-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.parent-card{scroll-margin-top:24px}.parent-card>.panel{padding:0;border:0;margin-top:24px}.parent-card .approved-summary{margin-top:18px}.parent-card .approved-summary summary{cursor:pointer;color:var(--muted);font-size:14px;margin-bottom:16px}.parent-card .review-actions{grid-template-columns:1fr}.parent-card .fields{gap:18px}.member-edit{display:inline-block;font-size:13px;margin:0 0 14px;text-decoration:none;font-weight:650}.relationship{font-weight:400;color:var(--muted);font-size:13px}
.steps{list-style:none;display:flex;gap:8px;padding:0;margin:0 0 24px;flex-wrap:wrap;font-size:12px;color:var(--muted)}.steps li{display:flex;align-items:center;gap:6px}.steps li+li:before{content:'／';color:#adb9ad;margin-right:2px}.steps span{display:inline-grid;place-items:center;width:22px;height:22px;border-radius:50%;background:#eef2ec;font-size:11px}.steps [aria-current]{color:var(--green);font-weight:700}.steps [aria-current] span{background:var(--green);color:white}
.family-details{margin-top:24px;scroll-margin-top:24px}.family-details.is-editing{display:grid;grid-template-columns:minmax(0,.85fr) minmax(0,1.15fr);gap:24px;align-items:start}.family-editor{min-width:0}.editor-toolbar{display:flex;justify-content:flex-end;margin-bottom:12px}.editor-toolbar a{font-size:14px}.family-details.is-editing .unified-family{margin-top:0}.family-display .member:last-child{padding-bottom:0}.unified-family{margin-top:24px}.unified-family>h2{margin-bottom:12px}.section-heading{margin:32px 0 18px}.section-heading p{font-size:14px;color:var(--muted)}.adult-row{margin:0 0 22px;border:1px solid var(--line);border-radius:12px;padding:22px;min-width:0}.adult-row legend{font-weight:650;padding:0 8px}.adult-toolbar{display:flex;justify-content:flex-end;align-items:center;gap:12px;margin-bottom:18px}.adult-fields{display:grid;gap:20px}.remove-notice{display:none;color:#934330}.is-removed .adult-fields{display:none}.is-removed .remove-notice{display:block}.is-removed{background:#faf1ed}.family-reason{margin-top:28px;margin-bottom:18px}.unified-family .review-actions form{display:grid;gap:18px}form{margin:0}.fields{display:grid;gap:22px}.field{display:flex;flex-direction:column;gap:7px;min-width:0}.field label{font-size:14px;font-weight:650}.required{font-size:11px;font-weight:400;color:var(--muted);margin-left:5px}.field input,.field textarea,.field select{display:block;width:100%;min-width:0;border:1px solid #bdcbbf;border-radius:9px;padding:11px 13px;background:#fff;color:#243d32;line-height:1.5;font-size:16px}.field input{min-height:48px}.field textarea{resize:vertical;min-height:100px}.field input:hover,.field textarea:hover{border-color:#7e9885}.field input:focus,.field textarea:focus{border-color:var(--green)}.field small{line-height:1.5}.actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:24px}.actions small{flex:1;min-width:150px}.button,button{display:inline-flex;align-items:center;justify-content:center;min-height:44px;gap:8px;padding:11px 18px;border:1px solid var(--green);border-radius:9px;background:var(--green);color:white;text-decoration:none;font-size:14px;line-height:1.5;font-weight:650;cursor:pointer;text-align:center;white-space:normal}.button:hover,button:hover{background:#214331}.secondary{background:white;color:var(--green);border-color:#b8c8bb}.secondary:hover{background:#eef4ed}.danger{background:white;color:#934330;border-color:#e3c5b9}.danger:hover{background:#fcf0eb}.withdraw{border-top:1px solid var(--line);margin-top:24px;padding-top:20px}.withdraw button{font-size:13px}.notice{padding:14px 16px;border-radius:10px;background:#eef4ee;color:#415e49;margin-bottom:22px;font-size:14px}.notice.returned{background:#fff5e4;color:#79591e}.notice p{margin:4px 0 0;white-space:pre-wrap}.empty{color:var(--muted);font-size:14px;padding:12px 0}.request-intro{color:var(--muted);font-size:14px}
.comparison{margin-top:26px;border-top:1px solid var(--line);padding-top:20px}.comparison summary{font-size:15px;font-weight:650;cursor:pointer;min-height:44px;padding:8px 0}.comparison .hint{font-size:13px;color:var(--muted);margin:8px 0 16px}.compare-row{padding:16px 0;border-top:1px solid #e6ece6}.compare-row h3{font-size:14px}.compare-values{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}.compare-values p{font-size:14px;margin:5px 0 0;white-space:pre-wrap;overflow-wrap:anywhere}.proposed{border-radius:8px;background:#f1f5f0;padding:10px 12px}.previous{padding:10px 0}.compare-row.changed .proposed{background:#eaf3e8}.review-actions{display:grid;gap:18px;margin-top:24px}.review-actions form{padding:18px;border:1px solid var(--line);border-radius:12px}.review-actions .actions{margin-top:14px}.review-actions textarea{min-height:80px}.review-actions small{margin-bottom:10px}
.history{margin-top:28px}.history>summary{cursor:pointer;display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:44px;font-weight:650;list-style:none}.history>summary::-webkit-details-marker{display:none}.history>summary:after{content:'＋';font-size:22px;font-weight:400}.history[open]>summary:after{content:'−'}.history-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:32px;margin-top:24px}.record{border-bottom:1px solid var(--line);padding:14px 0}.record summary{cursor:pointer;line-height:1.7;overflow-wrap:anywhere}.record summary small{margin:4px 0}.record .values{padding:16px;background:#f6f8f4;border-radius:9px;margin:12px 0}.record p{font-size:14px;white-space:pre-wrap}.timeline{list-style:none;margin:24px 0 0;padding:0}.timeline li{border-left:2px solid #dce6da;padding:0 0 20px 16px;font-size:14px;overflow-wrap:anywhere}.timeline p{margin:6px 0 0;white-space:pre-wrap}.timeline time{font-size:12px;color:var(--muted);display:block}.subject-list{list-style:none;padding:0;margin:0;display:grid;gap:12px}.subject-list a{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px;border:1px solid var(--line);border-radius:10px;text-decoration:none;font-weight:600}.subject-list a:after{content:'→';font-weight:400}.subject-list a:hover{background:#f0f5ee;border-color:#9aaf9e}.home-grid{display:grid;gap:24px}.history-note{margin-top:16px;font-size:12px;color:var(--muted)}
.family-map{margin-bottom:24px}.family-tree{padding:6px 0;--branch:#a6bca8}.family-branches{display:flex;justify-content:center;list-style:none;padding:0;margin:0}.family-branches li{flex:1;max-width:240px;min-width:0;position:relative;display:flex;justify-content:center;padding:24px 10px}.family-node{border:1px solid var(--line);border-radius:12px;background:#f7faf5;padding:14px 20px;min-width:0;width:100%;max-width:220px;text-align:center;overflow-wrap:anywhere}.family-node strong{display:block;font-size:16px;line-height:1.5}.node-role{display:block;font-size:12px;color:var(--muted);margin-bottom:4px}.family-node.adult{background:#f2f6f8;border-color:#cedde2}.family-node.child{background:#f0f6eb;border-color:#d3e0c9}.family-node.household{background:var(--green);color:white;max-width:260px}.household .node-role{color:#d8e7d8}.family-hub{display:flex;justify-content:center;position:relative;padding:0 10px}.family-hub.has-adults{padding-top:24px}.family-hub.has-children{padding-bottom:24px}.family-hub.has-adults:before,.family-hub.has-children:after{content:"";position:absolute;left:50%;height:24px;border-left:2px solid var(--branch)}.family-hub.has-adults:before{top:0}.family-hub.has-children:after{bottom:0}.family-branches li:before,.family-branches li:after{content:"";position:absolute;width:50%;height:24px;border-color:var(--branch);border-style:solid;border-width:0}.family-branches li:before{left:0;border-right-width:2px}.family-branches li:after{right:0}.family-branches.adults li{padding-top:0}.family-branches.adults li:before,.family-branches.adults li:after{bottom:0;border-bottom-width:2px}.family-branches.children li{padding-bottom:0}.family-branches.children li:before,.family-branches.children li:after{top:0;border-top-width:2px}.family-branches li:first-child:before{border-top-width:0;border-bottom-width:0}.family-branches li:last-child:after{border:0}.family-branches li:only-child:after{display:none}
@media(max-width:600px){.family-tree{padding-left:12px}.family-branches{display:block;border-left:2px solid var(--branch);margin-left:0}.family-branches li{max-width:none;padding:10px 0 10px 22px!important;justify-content:flex-start}.family-branches li:before{left:0;top:50%!important;bottom:auto!important;width:22px;height:0;border:0!important;border-top:2px solid var(--branch)!important}.family-branches li:after{display:none}.family-node{max-width:none;text-align:left;padding:12px 16px}.family-hub{justify-content:flex-start;padding:16px 0 16px 22px!important;border-left:2px solid var(--branch)}.family-hub:before,.family-hub:after{display:none}.family-hub .household{max-width:none}.family-hub .household:before{content:"";position:absolute;left:0;top:50%;width:22px;border-top:2px solid var(--branch)}.family-map .panel-footer{margin-top:16px}}
@media(max-width:760px){.topbar-inner{padding:14px 20px;flex-wrap:wrap}.header-actions{width:100%;justify-content:space-between;gap:16px}.signed-in-account{gap:12px}.brand{font-size:13px;gap:8px}.app-link{font-size:12px}main{padding:20px 16px 48px}.tabs{margin-bottom:24px}.page-head h1{font-size:26px}.page-head p{font-size:14px}.workspace,.history-grid,.parent-grid,.family-details.is-editing{grid-template-columns:1fr}.panel{padding:22px}.workspace{gap:20px}.history-grid{gap:24px}.stack{gap:20px}}
@media(max-width:420px){.topbar-inner{padding:12px 16px;flex-wrap:wrap}.panel{padding:20px}.compare-values{grid-template-columns:1fr;gap:4px}.actions{align-items:stretch;flex-direction:column}.actions button{width:100%}.actions small{min-width:0}.tabs a{flex:1;text-align:center;padding:10px}.panel-head{flex-wrap:wrap}.steps{gap:5px;font-size:11px}.review-actions form{padding:14px}}
`;

export type SignedInAccount = { name: string; email: string };
export function page(title: string, body: string, kind?: string, account?: SignedInAccount, basePath = "/profiles") {
  const caption = kind === "family" ? "家庭資料" : "個人資料";
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · SMZ Identity</title><style>${css}</style></head><body><header class="topbar"><div class="topbar-inner"><a class="brand" href="${basePath}"><span class="brand-mark">SMZ</span>家庭與個人資料</a><div class="header-actions">${basePath === "/admin/profile-reviews" ? '<a class="app-link" href="/admin">返回管理後台</a>' : ""}<a class="app-link" href="/">校園應用程式 ↗</a>${account ? `<section class="signed-in-account" aria-label="目前登入帳號"><div class="account-identity"><small>目前登入</small><strong>${e(account.name)}</strong><span>${e(account.email)}</span></div><form method="post" action="/profiles/sign-out"><button type="submit" class="secondary">登出</button></form></section>` : ""}</div></div></header><main><nav class="tabs" aria-label="資料導覽"><a href="${basePath}/family" ${kind === "family" ? 'aria-current="page"' : ""}>家庭資料</a><a href="${basePath}/person" ${kind === "person" ? 'aria-current="page"' : ""}>個人資料</a></nav><header class="page-head">${kind ? `<p class="eyebrow">${caption} / 資料維護</p>` : ""}<h1>${e(title)}</h1>${kind ? '<p>讓學校保持聯繫。您送出的變更，會在管理員或註冊組核准後更新。</p>' : ""}</header>${body}<p class="history-note">時間以臺灣時間顯示。</p></main></body></html>`;
}
